### PR TITLE
Add pcap to existing bigquery exporter queries

### PR DESCRIPTION
**Pull request by cristinaleonr**
- Add “pcap” to existing bigquery exporter queries

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/833)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/833)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[config/federation/prometheus/alerts.yml, line 821 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/833#-MgBPqqL8B1VvWpW1odM:-MgBPqqL8B1VvWpW1odN:b-f6r86v) ([raw file](https://github.com/m-lab/prometheus-support/blob/3e4d49fa5b985d7f3709d536d7a1779cc11d3b11/config/federation/prometheus/alerts.yml#L821)):*
> ```YAML
>   - alert: GardenerSlowProgress
>     expr: |
>       bq_gardener_dates_fully_parsed_last_day < 5
> ```

Is this processing rate adequate for the `Gardener_ParseTimeDifferenceTooOldOrMissing` alert?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/833)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/federation/prometheus/alerts.yml, line 821 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/833#-MgBPqqL8B1VvWpW1odM:-MgBZHbEBcWW25uehRBZ:b4bx6f8) ([raw file](https://github.com/m-lab/prometheus-support/blob/3e4d49fa5b985d7f3709d536d7a1779cc11d3b11/config/federation/prometheus/alerts.yml#L821)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this processing rate adequate for the `Gardener_ParseTimeDifferenceTooOldOrMissing` alert?
</blockquote></details>

I don't believe so. 

If we only process 5 dates per day, we'll only process about a year's worth of data (400 dates) in 80 days, but we have much more data than that.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/833)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[config/federation/prometheus/alerts.yml, line 821 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/833#-MgBPqqL8B1VvWpW1odM:-MgBdGM25RTKNgZBJP1H:b-i1xlw1) ([raw file](https://github.com/m-lab/prometheus-support/blob/3e4d49fa5b985d7f3709d536d7a1779cc11d3b11/config/federation/prometheus/alerts.yml#L821)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I don't believe so. 

If we only process 5 dates per day, we'll only process about a year's worth of data (400 dates) in 80 days, but we have much more data than that.
</blockquote></details>

What is the minimum threshold for the new platform datatypes (ndt7, annotation, pcap)?
What are some options for addressing this?

(we can also discuss in person)

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/833)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/federation/prometheus/alerts.yml, line 821 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/833#-MgBPqqL8B1VvWpW1odM:-MgC1X0c0vBPwXSTVzYX:b3eibrz) ([raw file](https://github.com/m-lab/prometheus-support/blob/3e4d49fa5b985d7f3709d536d7a1779cc11d3b11/config/federation/prometheus/alerts.yml#L821)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What is the minimum threshold for the new platform datatypes (ndt7, annotation, pcap)?
What are some options for addressing this?

(we can also discuss in person)
</blockquote></details>

Before, we were processing ~5 years (24 * 80 = 1920 dates) worth of data in 80 days. At the new rate, it will take at least 384 days to process that much data. 

We can either widen the window for the alert or allocate more parser instances to get closer to the old rate (if 2 instances parse 5 dates per day, 10 instances can parse 25 dates).

Happy to discuss during our call!

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/833)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[config/federation/prometheus/alerts.yml, line 821 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/833#-MgBPqqL8B1VvWpW1odM:-MgCXjxWEartR8uiLlCF:b-pvwpe6) ([raw file](https://github.com/m-lab/prometheus-support/blob/3e4d49fa5b985d7f3709d536d7a1779cc11d3b11/config/federation/prometheus/alerts.yml#L821)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Before, we were processing ~5 years (24 * 80 = 1920 dates) worth of data in 80 days. At the new rate, it will take at least 384 days to process that much data. 

We can either widen the window for the alert or allocate more parser instances to get closer to the old rate (if 2 instances parse 5 dates per day, 10 instances can parse 25 dates).

Happy to discuss during our call!
</blockquote></details>

What's a good number now based on the throughput possible with https://github.com/m-lab/etl/pull/1013 ?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/833)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/federation/prometheus/alerts.yml, line 821 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/833#-MgBPqqL8B1VvWpW1odM:-MgCaQOE-mWDh87G1Q7M:b-h3mfu6) ([raw file](https://github.com/m-lab/prometheus-support/blob/3e4d49fa5b985d7f3709d536d7a1779cc11d3b11/config/federation/prometheus/alerts.yml#L821)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What's a good number now based on the throughput possible with https://github.com/m-lab/etl/pull/1013 ?
</blockquote></details>

With two 2 replicas, the observed daily processing rate was ~11 dates per day. With 6 replicas, it should be ~33 dates/day.

Technically, no change is required here anymore. If we still want to update the threshold to 50% of the observed daily rate, then 17 would be a good number.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
I recommend reverting the changes to alerts.yml.

With that change, this :lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/833#-:-MgCdFOn0ulPxuOckyNZ:b-jrpvuz)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[config/federation/prometheus/alerts.yml, line 821 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/833#-MgBPqqL8B1VvWpW1odM:-MgCcU_8-ywvxhBJTEXt:b84meva) ([raw file](https://github.com/m-lab/prometheus-support/blob/3e4d49fa5b985d7f3709d536d7a1779cc11d3b11/config/federation/prometheus/alerts.yml#L821)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

With two 2 replicas, the observed daily processing rate was ~11 dates per day. With 6 replicas, it should be ~33 dates/day.

Technically, no change is required here anymore. If we still want to update the threshold to 50% of the observed daily rate, then 17 would be a good number.
</blockquote></details>

Great, we have a prediction of 33 dates/day. We can use the daily monitoring later this week to see if the real system matches our intuition. (3x was my estimate also, but I second guessed myself based on how quickly the other parsers could churn through the smaller datatypes. It's possible it could be higher than 3x, but I'm not sure, the bottleneck will continue to be whole-date processing of the pcap data).

I recommend preserving the original threshold at 24.

**Review by stephen-soltesz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/833)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/833)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/federation/prometheus/alerts.yml, line 821 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/833#-MgBPqqL8B1VvWpW1odM:-MgCfJjz8KG2n2gAQvHn:b-e55spc) ([raw file](https://github.com/m-lab/prometheus-support/blob/3e4d49fa5b985d7f3709d536d7a1779cc11d3b11/config/federation/prometheus/alerts.yml#L821)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Great, we have a prediction of 33 dates/day. We can use the daily monitoring later this week to see if the real system matches our intuition. (3x was my estimate also, but I second guessed myself based on how quickly the other parsers could churn through the smaller datatypes. It's possible it could be higher than 3x, but I'm not sure, the bottleneck will continue to be whole-date processing of the pcap data).

I recommend preserving the original threshold at 24.
</blockquote></details>

Great, done.

**Pull request merged**
