### PR TITLE
Adds snmp_exporter targets to gcp-service-discovery.

### PR DESCRIPTION
**Pull request by nkinkade**
This PR is complementary to [m-lab/operator/pull/152](https://github.com/m-lab/operator/pull/152).

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/82)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Hey, Nathan, I'm so sorry for the extremely long delay getting back to you on these. It is a reflection of my distraction rather than of the importance of this work. Thank you for your help setting up the snmp exporter. It is a very important component that you're building.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml, line 94 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/82#-KuvKvpRO5kb94ki1gIp:-KuvKvpRO5kb94ki1gIq:b-dvbb76) ([raw file](https://github.com/m-lab/prometheus-support/blob/9030da27294d3f81a0fb6e7d65a2ade0f08920f5/k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml#L94)):*
> ```YAML
>         # /etc/prometheus/prometheus.yml contains the M-Lab Prometheus config.
>         - mountPath: /etc/prometheus
>           name: prometheus-config
> ```

If we plan to use `snmp-targets`, then a new mountPath here for `snmp-targets` will also help.

---

*[k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml, line 130 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/82#-KuvKbG7RYkexmZcKVZl:-KuvKbG7RYkexmZcKVZm:b-aoirc4) ([raw file](https://github.com/m-lab/prometheus-support/blob/9030da27294d3f81a0fb6e7d65a2ade0f08920f5/k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml#L130)):*
> ```YAML
>                 "--http-target=/targets/blackbox-targets/ssh806.json",
>                 "--http-target=/targets/blackbox-targets/rsyncd.json",
>                 "--http-target=/targets/blackbox-targets/snmpexporter.json",
> ```

My suggestion for these paths is to use `snmp-targets` instead of `blackbox-targets`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/82#-:-KuvLHp0Jp257Q0QCma8:b9nkjcz)*

**Comment by nkinkade** [comment]
@stephen-soltesz: I think I've addressed your comments. PTAL? Thank you!

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml, line 94 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/82#-KuvKvpRO5kb94ki1gIp:-Kv-0pT0xmIRQkv63J8m:bt2vr1b) ([raw file](https://github.com/m-lab/prometheus-support/blob/9030da27294d3f81a0fb6e7d65a2ade0f08920f5/k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml#L94)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If we plan to use `snmp-targets`, then a new mountPath here for `snmp-targets` will also help.
</blockquote></details>

Fixed.

---

*[k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml, line 130 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/82#-KuvKbG7RYkexmZcKVZl:-Kv-0r1e8jJRh2Xnul6s:bt2vr1b) ([raw file](https://github.com/m-lab/prometheus-support/blob/9030da27294d3f81a0fb6e7d65a2ade0f08920f5/k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml#L130)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

My suggestion for these paths is to use `snmp-targets` instead of `blackbox-targets`.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/82#-:-Kv-0sUlHuaUXKDyLHel:b-a40nzp)*

**Comment by stephen-soltesz** [comment]
One change of `blackbox-targets` looks like it was missed. After fixing that :lgtm: !

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml, line 94 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/82#-KuvKvpRO5kb94ki1gIp:-Kv-JLS_1Bpj5j9d3GJl:bb6mt9b) ([raw file](https://github.com/m-lab/prometheus-support/blob/9030da27294d3f81a0fb6e7d65a2ade0f08920f5/k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml#L94)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

:+1:

---

*[k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml, line 130 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/82#-KuvKbG7RYkexmZcKVZl:-Kv-JR58tvgQhYL2rGf2:b-pgepp7) ([raw file](https://github.com/m-lab/prometheus-support/blob/9030da27294d3f81a0fb6e7d65a2ade0f08920f5/k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml#L130)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

This line is still using `blackbox-targets`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/82#-:-Kv-JY2pXWQiW5nPs5kr:bclpqxo)*

**Comment by nkinkade** [comment]
Fixed that one last `blackbox-targets` bit. Merging.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml, line 130 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/82#-KuvKbG7RYkexmZcKVZl:-Kv3Sju2yk6xOhPDmcop:bz0to61) ([raw file](https://github.com/m-lab/prometheus-support/blob/9030da27294d3f81a0fb6e7d65a2ade0f08920f5/k8s/mlab-sandbox/prometheus-federation/deployments/prometheus.yml#L130)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This line is still using `blackbox-targets`?
</blockquote></details>

Shoot. Fixed!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/82#-:-Kv3SoF5FrdlbvG_Liw6:b4svhhb)*

**Pull request merged**
