### PR TITLE
Pipeline alternative SLIs

### PR DESCRIPTION
**Pull request by cristinaleonr**
1. Added a new BigQuery exporter query to report the number of historical dates processed per datatype in the last 24 hours.
2. Adjusted `GardenerDailyParsingIsBehind` SLO to 3 days (in case the most recent date has not completed processing).
3. Replaced the `GardenerSlowProgress` alert with `GardenerHistoricalThroughputIsStalled`, which takes into consideration which data types are actually in processing and relaxes the SLO to one historical date per day.
4. Added the `GardenerFailureRateTooHighOrMissing` and `ParserFailureRateTooHighOrMissing` alerts to monitor when the rate of failures for the gardener or the parsers rises above 1%.

A dashboard to visualize the new metrics will also be created soon.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/858)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Great, smallish comments. Please consider `GardenerHistoricalThroughputIsStalled` will work on startup.

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/858#-:-MrXkcXXD2j7w-Y3S-At:biuvmz2)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[config/federation/bigquery/bq_gardener_historical.sql.template, line 57 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/858#-MrXi1fy0KwxXg2yABHS:-MrXi1fz4o3EHpivwzUw:bjzslts) ([raw file](https://github.com/m-lab/prometheus-support/blob/a261afcf78f933827c20290a7a4fcfce33f9134b/config/federation/bigquery/bq_gardener_historical.sql.template#L57)):*
> ```
>         BETWEEN TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 24 HOUR)
>             AND CURRENT_TIMESTAMP())
>    	AND date < DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) -- exclude daily.
> ```

nit: please do not mix tabs and spaces.
___
*[config/federation/prometheus/alerts.yml, line 846 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/858#-MrXiqe0BS-PNA1aVK_P:-MrXiqe0BS-PNA1aVK_Q:bh7u72y) ([raw file](https://github.com/m-lab/prometheus-support/blob/a261afcf78f933827c20290a7a4fcfce33f9134b/config/federation/prometheus/alerts.yml#L846)):*
> ```YAML
>       increase(gardener_jobs_total{status="success"}[1d]) > 0
>         UNLESS ON(datatype) bq_gardener_historical_throughput > 0
>     for: 10m
> ```

I'm imagining initial conditions. I think this alert timeout wants to be longer. Imagine startup when `gardener_jobs_total` is > 0 and `bq_gardener_historical_throughtput` does not yet exist.

Alternately, we may be able to use an offset (https://prometheus.io/docs/prometheus/latest/querying/basics/#offset-modifier) to make sure the metrics are more closely aligned.
___
*[config/federation/prometheus/alerts.yml, line 875 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/858#-MrXkHcc0INZMeNR6YqH:-MrXkHcc0INZMeNR6YqI:b-lqmbtk) ([raw file](https://github.com/m-lab/prometheus-support/blob/a261afcf78f933827c20290a7a4fcfce33f9134b/config/federation/prometheus/alerts.yml#L875)):*
> ```YAML
> # in the last hour rises above 1% or the number of total tasks is not reported.
>   - alert: ParserFailureRateTooHighOrMissing
>     expr: (sum(rate(etl_task_total{status!="OK", cluster="data-processing"}[1h])) by (datatype) /
> ```

nit: I know you're working with what's already there. So, this is not for this PR; it's just a general aside - we probably don't want N ways of saying "success". 
___
*[config/federation/prometheus/prometheus.yml.template, line 399 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/858#-MrXhV7Z3kcIV4D1E0bo:-MrXhV7Z3kcIV4D1E0bp:b1nzcy8) ([raw file](https://github.com/m-lab/prometheus-support/blob/a261afcf78f933827c20290a7a4fcfce33f9134b/config/federation/prometheus/prometheus.yml.template#L399)):*
> ```
>         - 'kubelet_volume_stats_capacity_bytes{persistentvolumeclaim="auto-prometheus-ssd0"}'
>         - 'gardener_jobs_total'
>         - 'etl_task_total'
> ```

:+1: good.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/858)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/federation/bigquery/bq_gardener_historical.sql.template, line 57 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/858#-MrXi1fy0KwxXg2yABHS:-MrYfs2I57aLRkoSiOjI:bs0ghc2) ([raw file](https://github.com/m-lab/prometheus-support/blob/a261afcf78f933827c20290a7a4fcfce33f9134b/config/federation/bigquery/bq_gardener_historical.sql.template#L57)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: please do not mix tabs and spaces.
</blockquote></details>

I looked at other files to find a convention, but some of them use 2 spaces (https://github.com/m-lab/prometheus-support/blob/master/config/federation/bigquery/bq_annotation.sql) and others use 4 (https://github.com/m-lab/prometheus-support/blob/master/config/federation/bigquery/bq_ndt_worldmap_server.sql). 

I'm using 2 spaces throughout now.
___
*[config/federation/prometheus/alerts.yml, line 846 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/858#-MrXiqe0BS-PNA1aVK_P:-MrYgRFNC4OUz8yoAa8h:b-fh9hlj) ([raw file](https://github.com/m-lab/prometheus-support/blob/a261afcf78f933827c20290a7a4fcfce33f9134b/config/federation/prometheus/alerts.yml#L846)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm imagining initial conditions. I think this alert timeout wants to be longer. Imagine startup when `gardener_jobs_total` is > 0 and `bq_gardener_historical_throughtput` does not yet exist.

Alternately, we may be able to use an offset (https://prometheus.io/docs/prometheus/latest/querying/basics/#offset-modifier) to make sure the metrics are more closely aligned.
</blockquote></details>

Good point. I changed it to 3 hours and 10 minutes since the 3h deployment runs the queries every 3 hours.
___
*[config/federation/prometheus/alerts.yml, line 875 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/858#-MrXkHcc0INZMeNR6YqH:-MrYgf9Y0wVjm2H2cujE:b-wr3hzn) ([raw file](https://github.com/m-lab/prometheus-support/blob/a261afcf78f933827c20290a7a4fcfce33f9134b/config/federation/prometheus/alerts.yml#L875)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: I know you're working with what's already there. So, this is not for this PR; it's just a general aside - we probably don't want N ways of saying "success". 
</blockquote></details>

Agreed. I could change the recorded value under the "status" label for the new metric (`gardener_jobs_total`) to "OK" instead of "success" for consistency. Though I kind of like "success" better than "OK".

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Please take a closer look at `GardenerHistoricalThroughputIsStalled`. Otherwise, lgtm.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/858#-:-MrZGTsW0n5vMDW6FNCF:b-dspc7a)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[config/federation/bigquery/bq_gardener_historical.sql.template, line 57 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/858#-MrXi1fy0KwxXg2yABHS:-MrZFCBT8hVwSoYXVphg:by874ih) ([raw file](https://github.com/m-lab/prometheus-support/blob/a261afcf78f933827c20290a7a4fcfce33f9134b/config/federation/bigquery/bq_gardener_historical.sql.template#L57)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I looked at other files to find a convention, but some of them use 2 spaces (https://github.com/m-lab/prometheus-support/blob/master/config/federation/bigquery/bq_annotation.sql) and others use 4 (https://github.com/m-lab/prometheus-support/blob/master/config/federation/bigquery/bq_ndt_worldmap_server.sql). 

I'm using 2 spaces throughout now.
</blockquote></details>

Thank you for check.
___
*[config/federation/prometheus/alerts.yml, line 846 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/858#-MrXiqe0BS-PNA1aVK_P:-MrZFQED6AhCYPNPm6vL:b-ksacu9) ([raw file](https://github.com/m-lab/prometheus-support/blob/a261afcf78f933827c20290a7a4fcfce33f9134b/config/federation/prometheus/alerts.yml#L846)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Good point. I changed it to 3 hours and 10 minutes since the 3h deployment runs the queries every 3 hours.
</blockquote></details>

Okay, I think this might still generate false positives under some conditions. Gardener will make progress before `bq_gardener_historical_throughput` exists for the previous day.  I think `increase(gardener_jobs_total{status="success"}[1d] offset 24h)` would be closer. Please experiment with `offset XX` to get a sense for it yourself.
___
*[config/federation/prometheus/alerts.yml, line 875 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/858#-MrXkHcc0INZMeNR6YqH:-MrZGMSm-lDLRvrefxRG:be21wjw) ([raw file](https://github.com/m-lab/prometheus-support/blob/a261afcf78f933827c20290a7a4fcfce33f9134b/config/federation/prometheus/alerts.yml#L875)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Agreed. I could change the recorded value under the "status" label for the new metric (`gardener_jobs_total`) to "OK" instead of "success" for consistency. Though I kind of like "success" better than "OK".
</blockquote></details>

I also like "success" better :)

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/858)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr and @stephen-soltesz)

___
*[config/federation/prometheus/alerts.yml, line 846 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/858#-MrXiqe0BS-PNA1aVK_P:-Mrd2G-85LXX1GAiW-0Q:bavv2h3) ([raw file](https://github.com/m-lab/prometheus-support/blob/a261afcf78f933827c20290a7a4fcfce33f9134b/config/federation/prometheus/alerts.yml#L846)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Okay, I think this might still generate false positives under some conditions. Gardener will make progress before `bq_gardener_historical_throughput` exists for the previous day.  I think `increase(gardener_jobs_total{status="success"}[1d] offset 24h)` would be closer. Please experiment with `offset XX` to get a sense for it yourself.
</blockquote></details>

Okay, I plotted it with and without the offset and I see what you mean. Updated!

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 8 of 9 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/858#-:-Mrd4W0z7MDcvvks8IAC:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
