### PR TITLE
Configs for downloader monitoring

### PR DESCRIPTION
**Pull request by jlm123hi**
I'm sure that this could be done better, don't hesitate to tell me how. But it should sufficiently monitor the downloader service and make those stats appear in prometheus/grafana.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/76)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 16 of 20 files at r1.
Review status: 16 of 20 files reviewed at latest revision, 5 unresolved discussions.

---

*[.travis.yml, line 57 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqPdPapqciJp7FK9BZF:-KqPdPapqciJp7FK9BZG:b380t7p) ([raw file](https://github.com/m-lab/prometheus-support/blob/2577f34992af8bf57736185b4c715c3105346395/.travis.yml#L57)):*
> ```YAML
>     all_branches: true
>     condition: $TRAVIS_BRANCH == sandbox-* && $TRAVIS_EVENT_TYPE == push
>     
> ```

Looks like extra spaces here.

Vim can highlight eol whitespace with a rule like this:

```
highlight ExtraWhitespace ctermbg=red guibg=red                                
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/ 
```

---

*[config/federation/prometheus/prometheus.yml, line 313 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqPcTEH2So5h0OjBxJE:-KqPcTEH2So5h0OjBxJF:bxow6pa) ([raw file](https://github.com/m-lab/prometheus-support/blob/2577f34992af8bf57736185b4c715c3105346395/config/federation/prometheus/prometheus.yml#L313)):*
> ```YAML
>         - 'up{application="scraper"}'
>         - 'up{application="scraper-sync"}'
>         - '{deployment="downloader"}'
> ```

During one of our earlier conversations I said something like "there are more options" for getting data out of the cluster instance of prometheus. But, I never elaborated.

In the current design the federation instance of prometheus is imagined to aggregate statistics for alerting.

Grafana supports multiple data sources. And, the (preferable, I think) alternative to loading all metrics from the downloader cluster into the federation cluster would be to add a new datasource to grafana and plot metrics by querying the downloader's prometheus instance directly.

Right now we plan to create a "grafana sync" service that updates Grafana with new data sources, but also right now that doesn't exist yet and adding a new data source is manual.

So, until there are specific alerts to define on the downloader service, my preference would be to remove this line and rely on a data source in grafana for the downloader prometheus instance.

---

*[k8s/mlab-oti/downloader/deployments/prometheus.yml, line 85 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqPcfxVj6sfY7qkFZL6:-KqPcfxWKHdecWHIQgeh:bkzevz6) ([raw file](https://github.com/m-lab/prometheus-support/blob/2577f34992af8bf57736185b4c715c3105346395/k8s/mlab-oti/downloader/deployments/prometheus.yml#L85)):*
> ```YAML
>         args: ["-config.file=/etc/prometheus/prometheus.yml",
>                "-storage.local.path=/prometheus",
>                #"-storage.local.target-heap-size=75161927680",
> ```

It's okay to remove this since we don't want this here.

If the resource requests of 2Gi is sufficient, I suggest removing all the following -storage.local args (but keep the -storage.local.path parameter) and use the default values. The other values here were set to accommodate the highmem scenario and may disproportionate to a more constrained environment.

---

*[k8s/mlab-sandbox/downloader/deployments/prometheus.yml, line 85 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqPd4b7kgE0iRH3QTBy:-KqPd4b7kgE0iRH3QTBz:brhumzt) ([raw file](https://github.com/m-lab/prometheus-support/blob/2577f34992af8bf57736185b4c715c3105346395/k8s/mlab-sandbox/downloader/deployments/prometheus.yml#L85)):*
> ```YAML
>         args: ["-config.file=/etc/prometheus/prometheus.yml",
>                "-storage.local.path=/prometheus",
>                #"-storage.local.target-heap-size=75161927680",
> ```

Same here.

---

*[k8s/mlab-staging/downloader/deployments/prometheus.yml, line 85 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqPdE37Wam1Mw_uEYFU:-KqPdE37Wam1Mw_uEYFV:bchbwlg) ([raw file](https://github.com/m-lab/prometheus-support/blob/2577f34992af8bf57736185b4c715c3105346395/k8s/mlab-staging/downloader/deployments/prometheus.yml#L85)):*
> ```YAML
>         args: ["-config.file=/etc/prometheus/prometheus.yml",
>                "-storage.local.path=/prometheus",
>                #"-storage.local.target-heap-size=75161927680",
> ```

And, here too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/76)*

**Comment by jlm123hi** [comment]
Review status: 16 of 20 files reviewed at latest revision, 5 unresolved discussions.

---

*[.travis.yml, line 57 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqPdPapqciJp7FK9BZF:-KqSzWIUnCxwBYqAuDGR:b-896fix) ([raw file](https://github.com/m-lab/prometheus-support/blob/2577f34992af8bf57736185b4c715c3105346395/.travis.yml#L57)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Looks like extra spaces here.

Vim can highlight eol whitespace with a rule like this:

```
highlight ExtraWhitespace ctermbg=red guibg=red                                
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/ 
```
</blockquote></details>

Done.

---

*[config/federation/prometheus/prometheus.yml, line 313 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqPcTEH2So5h0OjBxJE:-KqTCCv6TytEqmMp-ov9:bbwci0a) ([raw file](https://github.com/m-lab/prometheus-support/blob/2577f34992af8bf57736185b4c715c3105346395/config/federation/prometheus/prometheus.yml#L313)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

During one of our earlier conversations I said something like "there are more options" for getting data out of the cluster instance of prometheus. But, I never elaborated.

In the current design the federation instance of prometheus is imagined to aggregate statistics for alerting.

Grafana supports multiple data sources. And, the (preferable, I think) alternative to loading all metrics from the downloader cluster into the federation cluster would be to add a new datasource to grafana and plot metrics by querying the downloader's prometheus instance directly.

Right now we plan to create a "grafana sync" service that updates Grafana with new data sources, but also right now that doesn't exist yet and adding a new data source is manual.

So, until there are specific alerts to define on the downloader service, my preference would be to remove this line and rely on a data source in grafana for the downloader prometheus instance.
</blockquote></details>

I've added a new alert, which I really should have added to the first iteration of this pull request.  I agree that adding it directly to grafana would be better, though. If there's a way to do that and also send alerts (that isn't absolutely abhorrent), I'd be all for it.

---

*[k8s/mlab-oti/downloader/deployments/prometheus.yml, line 85 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqPcfxVj6sfY7qkFZL6:-KqSzSAi7ii9p_7p3J7y:b-896fix) ([raw file](https://github.com/m-lab/prometheus-support/blob/2577f34992af8bf57736185b4c715c3105346395/k8s/mlab-oti/downloader/deployments/prometheus.yml#L85)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It's okay to remove this since we don't want this here.

If the resource requests of 2Gi is sufficient, I suggest removing all the following -storage.local args (but keep the -storage.local.path parameter) and use the default values. The other values here were set to accommodate the highmem scenario and may disproportionate to a more constrained environment.
</blockquote></details>

Done.

---

*[k8s/mlab-sandbox/downloader/deployments/prometheus.yml, line 85 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqPd4b7kgE0iRH3QTBy:-KqSzSxwLbChDkUIHC-W:b-896fix) ([raw file](https://github.com/m-lab/prometheus-support/blob/2577f34992af8bf57736185b4c715c3105346395/k8s/mlab-sandbox/downloader/deployments/prometheus.yml#L85)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---

*[k8s/mlab-staging/downloader/deployments/prometheus.yml, line 85 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqPdE37Wam1Mw_uEYFU:-KqSzT_YbHFQnYIWXHnw:b-896fix) ([raw file](https://github.com/m-lab/prometheus-support/blob/2577f34992af8bf57736185b4c715c3105346395/k8s/mlab-staging/downloader/deployments/prometheus.yml#L85)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

And, here too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/76)*

**Comment by stephen-soltesz** [comment]
Reviewed 4 of 5 files at r2.
Review status: 19 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

*[config/federation/prometheus/alerts.yml, line 221 at r2](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqTTe3fQq8IdxgqIKuV:-KqTTe3fQq8IdxgqIKuW:b-wc07da) ([raw file](https://github.com/m-lab/prometheus-support/blob/4baf67a363123a21ced51891cf4faa9a3b799a6c/config/federation/prometheus/alerts.yml#L221)):*
> ```YAML
> # DownloaderIsFailingToUpdate: The downloader hasn't successfully retrieved the files in at least 21 hours, meaning that at least the last two download attempts have failed.
> ALERT DownloaderIsFailingToUpdate
>   IF time()-downloader_Last_Successful_Time > (21 * 60 * 60)
> ```

Please update these metrics to match the suggestions in https://github.com/m-lab/downloader/pull/3

---

*[config/federation/prometheus/prometheus.yml, line 313 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqPcTEH2So5h0OjBxJE:-KqTLGH4pfI-2EvAwJUm:b4uobam) ([raw file](https://github.com/m-lab/prometheus-support/blob/2577f34992af8bf57736185b4c715c3105346395/config/federation/prometheus/prometheus.yml#L313)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

I've added a new alert, which I really should have added to the first iteration of this pull request.  I agree that adding it directly to grafana would be better, though. If there's a way to do that and also send alerts (that isn't absolutely abhorrent), I'd be all for it.
</blockquote></details>

We can do that. And, I think that's the right split between the federation config and the cluster config.

So here, I would like to see the federation prometheus configuration only collecting specific metrics used by alerts. In this case, the query would be only for `downloader_last_success_time_seconds`.

And, we can rely on Grafana's data source to make all metrics available in a more complete dashboard.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/76)*

**Comment by jlm123hi** [comment]
Review status: 19 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

*[config/federation/prometheus/alerts.yml, line 221 at r2](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqTTe3fQq8IdxgqIKuV:-KqU1bXNy1xlceCdINLQ:b-896fix) ([raw file](https://github.com/m-lab/prometheus-support/blob/4baf67a363123a21ced51891cf4faa9a3b799a6c/config/federation/prometheus/alerts.yml#L221)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please update these metrics to match the suggestions in https://github.com/m-lab/downloader/pull/3
</blockquote></details>

Done.

---

*[config/federation/prometheus/prometheus.yml, line 313 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqPcTEH2So5h0OjBxJE:-KqU1dicgBqUdEkWm4al:b-dk2tni) ([raw file](https://github.com/m-lab/prometheus-support/blob/2577f34992af8bf57736185b4c715c3105346395/config/federation/prometheus/prometheus.yml#L313)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We can do that. And, I think that's the right split between the federation config and the cluster config.

So here, I would like to see the federation prometheus configuration only collecting specific metrics used by alerts. In this case, the query would be only for `downloader_last_success_time_seconds`.

And, we can rely on Grafana's data source to make all metrics available in a more complete dashboard.
</blockquote></details>

I've made the change. But if the addition of a data source to grafana needs to happen via the website, then I certainly don't have the permissions to do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/76)*

**Comment by stephen-soltesz** [comment]
Reviewed 1 of 2 files at r3.
Review status: 20 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

*[config/federation/prometheus/prometheus.yml, line 313 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-KqPcTEH2So5h0OjBxJE:-KqU4knBwcJ83X8zTP5F:b-6cmxhr) ([raw file](https://github.com/m-lab/prometheus-support/blob/2577f34992af8bf57736185b4c715c3105346395/config/federation/prometheus/prometheus.yml#L313)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

I've made the change. But if the addition of a data source to grafana needs to happen via the website, then I certainly don't have the permissions to do it.
</blockquote></details>

Oh just sign up for an account and I can give you all the permissions you'd like.

e.g. http://status-mlab-sandbox.measurementlab.net:3000/login -> Sign up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/76)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/76#-:-KqU5B_urmHzpJ-czThx:bnfp4nl)*

**Pull request merged**
