### PR TITLE
Add kubernetes configuration for a sandbox Prometheus deployment

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds several new kubernetes configuration files and supporting updates to the README.

This change provides a template for deploying prometheus to kubernetes clusters on other M-Lab GCP projects. This will also serve as a foundation for automated deployments / updates in the future.

This change moves the location of legacy configuration files from `/etc/prometheus/legacy` to `/legacy-targets/`. This allows the legacy target configuration to be stored on persistent disk as well as metric data so we can update prometheus versions without losing configuration.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/5)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Hi, @salarcon215, please keep playing with this Monday. I do not want to move ahead without you.

**Comment by pboothe** [comment]
LGTM. Thanks for figuring out the persistent volumes thing.

**Comment by salarcon215** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 13 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/5#-Ke9Y1Ov7EhZ7cB43UcD:-Ke9Y1Ov7EhZ7cB43UcE:b-mtesl9) ([raw file](https://github.com/m-lab/prometheus-support/blob/339f92da00b9d1653c1bb25065a8443549246583/README.md#L13)):*
> ```Markdown
>     DOCKERUSER=$USER   # Use your actual dockerhub username.
>     sudo docker login
>     sudo docker build -t prometheus-server .
> ```

For `.` to work here, the user needs to be in the right directory: prometheus-support/prometheus. I often want a shorthand for "the directory where you cloned the repo". Is there a convention for that? Maybe $GITHOME or something?

---

*[README.md, line 80 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/5#-Ke9ujK_j1u8UQf3163Z:-Ke9ujK_j1u8UQf3163_:b-uphnv1) ([raw file](https://github.com/m-lab/prometheus-support/blob/339f92da00b9d1653c1bb25065a8443549246583/README.md#L80)):*
> ```Markdown
>     podname=$( kubectl get pods -o name --selector='run=prometheus-server' )
>     kubectl cp <filename.json> ${podname##*/}:/legacy-targets/
> ```

I believe you that this is how to add targets to a running deployment. But to make those targets part of the standard deployment, is that a step that we'll add in later additions? I don't see a "legacy-targets" directory in this repo.

---

*[README.md, line 103 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/5#-Ke9vlqztyQakv2SXGI5:-Ke9vlr-jbTgPHrkN_Wa:b-8con2h) ([raw file](https://github.com/m-lab/prometheus-support/blob/339f92da00b9d1653c1bb25065a8443549246583/README.md#L103)):*
> ```Markdown
> 
> [dns]: https://github.com/kubernetes-incubator/external-dns
> ```

Does it make sense to add a line about discovering/confirming/changing the gcloud project that the user is set to use?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/5)*

**Comment by salarcon215** [comment]
With the few small content notes I made inline, LGTM.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/5#-:-Ke9x3Y_g1B0GgVb7wkY:b-ntuzvg)*

**Comment by stephen-soltesz** [comment]
Thanks for the reviews!

I update the README with the hint you suggested.

---

Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 13 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/5#-Ke9Y1Ov7EhZ7cB43UcD:-KeA__Zxlx4FPiDSn3Dz:b9vkx1f) ([raw file](https://github.com/m-lab/prometheus-support/blob/339f92da00b9d1653c1bb25065a8443549246583/README.md#L13)):*
<details><summary><i>Previously, salarcon215 wrote…</i></summary><blockquote>

For `.` to work here, the user needs to be in the right directory: prometheus-support/prometheus. I often want a shorthand for "the directory where you cloned the repo". Is there a convention for that? Maybe $GITHOME or something?
</blockquote></details>

Good question. I don't know if there's a convention. But, it would be a good idea to add a reminder.

I'm preparing a change that will eliminate the need for us to build our own image of the prometheus-server by automatically mounting the prometheus.yml configuration via kubernetes instead, so I'm not updating this text for now since the next PR should delete it.

---

*[README.md, line 80 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/5#-Ke9ujK_j1u8UQf3163Z:-KeA_5vFmsO4xuxMMfoA:bewtu09) ([raw file](https://github.com/m-lab/prometheus-support/blob/339f92da00b9d1653c1bb25065a8443549246583/README.md#L80)):*
<details><summary><i>Previously, salarcon215 wrote…</i></summary><blockquote>

I believe you that this is how to add targets to a running deployment. But to make those targets part of the standard deployment, is that a step that we'll add in later additions? I don't see a "legacy-targets" directory in this repo.
</blockquote></details>

Right. I'm imagining that `mlabconfig.py` will support a mode that generates json in the right format for the new sidestream exporter once the new npad package is deployed widely.

---

*[README.md, line 103 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/5#-Ke9vlqztyQakv2SXGI5:-KeAa2K35A_smz8C50JF:b-zfyhrg) ([raw file](https://github.com/m-lab/prometheus-support/blob/339f92da00b9d1653c1bb25065a8443549246583/README.md#L103)):*
<details><summary><i>Previously, salarcon215 wrote…</i></summary><blockquote>

Does it make sense to add a line about discovering/confirming/changing the gcloud project that the user is set to use?
</blockquote></details>

It does. I've added a note in the `Start` section to confirm that operations are on the correct kubernetes cluster first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/5#-:-KeAbXUZyJxI5pxi-wUP:b-1s2keb)*

**Pull request merged**
