### PR TITLE
Add preliminary scamper detail dashboard

### PR DESCRIPTION
**Pull request by gfr10598**
This dashboard has basic metrics to track trace volume, latency, and success rate.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/828)

### CODE REVIEW

**Comment by gfr10598** [comment]
Running in sandbox at https://grafana.mlab-sandbox.measurementlab.net/d/7l1KQtR7k/exp-scamper-detail

**Comment by SaiedKazemi** [comment]
Thanks for setting up this dashboard.

**Comment by SaiedKazemi** [comment]
:lgtm:

**Review by SaiedKazemi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/828)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
