### PR TITLE
Adds a new AlertManager alert for the snmp_exporter service.

### PR DESCRIPTION
**Pull request by nkinkade**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/114)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[config/federation/prometheus/alerts.yml, line 233 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-KxUznUgBy1cSP_P5oiQ:-KxUznUhF5_gg5yW0Fx1:bp6yus) ([raw file](https://github.com/m-lab/prometheus-support/blob/985d73dc7d00a01f580b9767f528a4476b4c0118/config/federation/prometheus/alerts.yml#L233)):*
> ```YAML
> # Prometheus is unable to get data from the snmp_exporter service.
> ALERT SnmpExporterDown
>   IF up{job="snmp-exporter"} == 0
> ```

I suggest also adding an `absent()` alert. For example, if someone removes it from the prometheus.yml config.

---

*[config/federation/prometheus/alerts.yml, line 234 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-KxUzpcRTm0hRgBXDmen:-KxUzpcRTm0hRgBXDmeo:b-g6f5kz) ([raw file](https://github.com/m-lab/prometheus-support/blob/985d73dc7d00a01f580b9767f528a4476b4c0118/config/federation/prometheus/alerts.yml#L234)):*
> ```YAML
> ALERT SnmpExporterDown
>   IF up{job="snmp-exporter"} == 0
>   FOR 10m
> ```

How long does the VM recreation take? And, how long are we comfortable missing switch data if the service goes down for another reason?

---

*[config/federation/prometheus/alerts.yml, line 239 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-KxUzskpcbCqif6l752m:-KxUzskpcbCqif6l752n:bjog64p) ([raw file](https://github.com/m-lab/prometheus-support/blob/985d73dc7d00a01f580b9767f528a4476b4c0118/config/federation/prometheus/alerts.yml#L239)):*
> ```YAML
>   }
>   ANNOTATIONS {
>     summary = "Prometheus think that the snmp_exporter service is down on {{ $labels.instance }}.",
> ```

typo: s/think/thinks/

But I suggest leaving out "Prometheus think that". If the alert is firing we should speak of and act as though it is real. These alerts should not be spurious or flaky. If they are that's a bug with the alert or the monitoring that we must fix. We will not allow Prometheus alerts to be anything like Nagios alerts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/114)*

**Comment by nkinkade** [comment]
PTAL?

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[config/federation/prometheus/alerts.yml, line 233 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-KxUznUgBy1cSP_P5oiQ:-KxV5PkO6GRHflNk9k7g:biddpfq) ([raw file](https://github.com/m-lab/prometheus-support/blob/985d73dc7d00a01f580b9767f528a4476b4c0118/config/federation/prometheus/alerts.yml#L233)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest also adding an `absent()` alert. For example, if someone removes it from the prometheus.yml config.
</blockquote></details>

Done. Thanks for the explanation on the mlab VC.

---

*[config/federation/prometheus/alerts.yml, line 234 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-KxUzpcRTm0hRgBXDmen:-KxV5TrJPhJlm69Wkxbp:b-nncwtg) ([raw file](https://github.com/m-lab/prometheus-support/blob/985d73dc7d00a01f580b9767f528a4476b4c0118/config/federation/prometheus/alerts.yml#L234)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

How long does the VM recreation take? And, how long are we comfortable missing switch data if the service goes down for another reason?
</blockquote></details>

If you look at the [build history for the m-lab/prometheus-snmp-exporter repository in Travis-CI](https://travis-ci.com/m-lab/prometheus-snmp-exporter/builds), all the builds are less than 5 minutes, so I think 10 minutes seems reasonable.

---

*[config/federation/prometheus/alerts.yml, line 239 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-KxUzskpcbCqif6l752m:-KxV5jQFg-tg1YPKmc6n:bt2vr1b) ([raw file](https://github.com/m-lab/prometheus-support/blob/985d73dc7d00a01f580b9767f528a4476b4c0118/config/federation/prometheus/alerts.yml#L239)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

typo: s/think/thinks/

But I suggest leaving out "Prometheus think that". If the alert is firing we should speak of and act as though it is real. These alerts should not be spurious or flaky. If they are that's a bug with the alert or the monitoring that we must fix. We will not allow Prometheus alerts to be anything like Nagios alerts.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-:-KxV5kzX5HLiTHV6VaJS:b-833305)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[config/federation/prometheus/alerts.yml, line 233 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-KxUznUgBy1cSP_P5oiQ:-KxV5g9v68eBQLasrr7w:bn6ga9) ([raw file](https://github.com/m-lab/prometheus-support/blob/985d73dc7d00a01f580b9767f528a4476b4c0118/config/federation/prometheus/alerts.yml#L233)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Done. Thanks for the explanation on the mlab VC.
</blockquote></details>

I'm sorry. I wasn't being clear. The original alert definition you had was great.

```
IF up{job="snmp-exporter"} == 0
...
```

That checks for the `up` metric with the "snmp-exporter" label that equal zero. i.e. that are down / failed to collect.

I'm suggesting that in addition to that one, we add a second alert definition using `absent()`.

```
IF absent(up{job="snmp-exporter"})
...
```

In this case we don't use `== 0` because we want to know if there are *any* `up` metrics for the snmp-exporter job. In this case, if `up{job="snmp-exporter"} == 0` is firing, then `absent(up{job="snmp-exporter"})` will not be firing. And, if `absent(up{job="snmp-exporter"})` is firing then `up{job="snmp-exporter"} == 0` could not be firing (because no `up` metrics exist to equal zero).

These conditions are mutually exclusive but both are necessary to cover two distinct failure modes (down server and missing configuration).

---

*[config/federation/prometheus/alerts.yml, line 234 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-KxUzpcRTm0hRgBXDmen:-KxV6pS-XBWMiOPFEjTb:bj6bcrw) ([raw file](https://github.com/m-lab/prometheus-support/blob/985d73dc7d00a01f580b9767f528a4476b4c0118/config/federation/prometheus/alerts.yml#L234)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

If you look at the [build history for the m-lab/prometheus-snmp-exporter repository in Travis-CI](https://travis-ci.com/m-lab/prometheus-snmp-exporter/builds), all the builds are less than 5 minutes, so I think 10 minutes seems reasonable.
</blockquote></details>

Great. Thank you for checking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/114)*

**Comment by nkinkade** [comment]
@stephen-soltesz: PTAL?

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[config/federation/prometheus/alerts.yml, line 233 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-KxUznUgBy1cSP_P5oiQ:-KxV8FNEbcmNYeQF-QU9:b-kz6k8t) ([raw file](https://github.com/m-lab/prometheus-support/blob/985d73dc7d00a01f580b9767f528a4476b4c0118/config/federation/prometheus/alerts.yml#L233)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm sorry. I wasn't being clear. The original alert definition you had was great.

```
IF up{job="snmp-exporter"} == 0
...
```

That checks for the `up` metric with the "snmp-exporter" label that equal zero. i.e. that are down / failed to collect.

I'm suggesting that in addition to that one, we add a second alert definition using `absent()`.

```
IF absent(up{job="snmp-exporter"})
...
```

In this case we don't use `== 0` because we want to know if there are *any* `up` metrics for the snmp-exporter job. In this case, if `up{job="snmp-exporter"} == 0` is firing, then `absent(up{job="snmp-exporter"})` will not be firing. And, if `absent(up{job="snmp-exporter"})` is firing then `up{job="snmp-exporter"} == 0` could not be firing (because no `up` metrics exist to equal zero).

These conditions are mutually exclusive but both are necessary to cover two distinct failure modes (down server and missing configuration).
</blockquote></details>

Ah. Got it. I think my latest commit fixes this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-:-KxV8NgoO-7Lv7_z_k4_:b-e77fnf)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[config/federation/prometheus/alerts.yml, line 232 at r2](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-KxVIB2TNjwdDCo8XSeE:-KxVIB2TNjwdDCo8XSeF:b-4rpy4p) ([raw file](https://github.com/m-lab/prometheus-support/blob/738d634307dadfbcd63a695e06eb95b07b14edf0/config/federation/prometheus/alerts.yml#L232)):*
> ```YAML
> 
> # Prometheus is unable to get data from the snmp_exporter service.
> ALERT SnmpExporterDown
> ```

Since the alert condition includes two things, please reflect this in the alert name, e.g. SnmpExporterDownOrMissing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-:-KxVINFUiqWTbdf7lOLp:bnfp4nl)*

**Comment by nkinkade** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[config/federation/prometheus/alerts.yml, line 232 at r2](https://reviewable.io:443/reviews/m-lab/prometheus-support/114#-KxVIB2TNjwdDCo8XSeE:-KxiADXuY4j-4gNpnLSB:b-lx4fjp) ([raw file](https://github.com/m-lab/prometheus-support/blob/738d634307dadfbcd63a695e06eb95b07b14edf0/config/federation/prometheus/alerts.yml#L232)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since the alert condition includes two things, please reflect this in the alert name, e.g. SnmpExporterDownOrMissing
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/114)*

**Pull request merged**
