### PR TITLE
Sets machine-dependent alerts to not alert on nodes in lame-duck mode.

### PR DESCRIPTION
**Pull request by nkinkade**
If a node has been put in lame-duck mode, then all bets are off for machine-dependent services. This PR negates an alert condition if the node is in lame-duck mode.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/118)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[config/federation/prometheus/alerts.yml, line 52 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/118#-Kxy8lkH813kKRhkoqbQ:-Kxy8lkH813kKRhkoqbR:bdwgn0d) ([raw file](https://github.com/m-lab/prometheus-support/blob/21390d150e667c2c6202c03b94c78f0a5fd8ca3f/config/federation/prometheus/alerts.yml#L52)):*
> ```YAML
>         AND ON(machine)
>            sum_over_time(probe_success{service="ssh806"}[20m]) / 20 >= 0.90
>         UNLESS ON(machine) lame_duck_node == 1
> ```

The logic looks good.

My suggestion is to either continue to indent the `UNLESS`, or to change the indent of sum_over_time.

The goal is readability. And I find either of these clearer. What do you think?

```
 IF sum_over_time(up{service="sidestream"}[10m]) == 0
       AND ON(machine)
          sum_over_time(probe_success{service="ssh806"}[20m]) / 20 >= 0.90
             UNLESS ON(machine)
                lame_duck_node == 1
```

```
 IF sum_over_time(up{service="sidestream"}[10m]) == 0
       AND ON(machine)
    sum_over_time(probe_success{service="ssh806"}[20m]) / 20 >= 0.90
       UNLESS ON(machine)
    lame_duck_node == 1
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/118)*

**Comment by stephen-soltesz** [comment]
Oh, when you get a chance, please sync with master and re-push to your branch so that mlab-sandbox is updated with the slow targets config.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/118#-:-KxyCCHEJHxZKOFN8155:b-1qrdga)*

**Comment by nkinkade** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[config/federation/prometheus/alerts.yml, line 52 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/118#-Kxy8lkH813kKRhkoqbQ:-KxyEUXQOcce2ycYB0lW:b388j0n) ([raw file](https://github.com/m-lab/prometheus-support/blob/21390d150e667c2c6202c03b94c78f0a5fd8ca3f/config/federation/prometheus/alerts.yml#L52)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The logic looks good.

My suggestion is to either continue to indent the `UNLESS`, or to change the indent of sum_over_time.

The goal is readability. And I find either of these clearer. What do you think?

```
 IF sum_over_time(up{service="sidestream"}[10m]) == 0
       AND ON(machine)
          sum_over_time(probe_success{service="ssh806"}[20m]) / 20 >= 0.90
             UNLESS ON(machine)
                lame_duck_node == 1
```

```
 IF sum_over_time(up{service="sidestream"}[10m]) == 0
       AND ON(machine)
    sum_over_time(probe_success{service="ssh806"}[20m]) / 20 >= 0.90
       UNLESS ON(machine)
    lame_duck_node == 1
```
</blockquote></details>

@stephen-soltesz: Would you be open to something like this?

```
 IF sum_over_time(up{service="sidestream"}[10m]) == 0
    AND ON(machine)
       sum_over_time(probe_success{service="ssh806"}[20m]) / 20 >= 0.90
    UNLESS ON(machine)
       lame_duck_node == 1
```

It seems somewhat awkward to me to have a 6-space indent and then suddenly have the indent go backward to 3 spaces. Indeed, 3- and 6-space indents themselves seem odd to me. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/118)*

**Comment by nkinkade** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[config/federation/prometheus/alerts.yml, line 52 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/118#-Kxy8lkH813kKRhkoqbQ:-KxyFGL0hBQV68XDlD-p:b-5e5jwc) ([raw file](https://github.com/m-lab/prometheus-support/blob/21390d150e667c2c6202c03b94c78f0a5fd8ca3f/config/federation/prometheus/alerts.yml#L52)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

@stephen-soltesz: Would you be open to something like this?

```
 IF sum_over_time(up{service="sidestream"}[10m]) == 0
    AND ON(machine)
       sum_over_time(probe_success{service="ssh806"}[20m]) / 20 >= 0.90
    UNLESS ON(machine)
       lame_duck_node == 1
```

It seems somewhat awkward to me to have a 6-space indent and then suddenly have the indent go backward to 3 spaces. Indeed, 3- and 6-space indents themselves seem odd to me. :)
</blockquote></details>

If you're feelings are strong on the matter, I'm fine with just going with your option two. I think I prefer an indent that resets instead of always increasing (that could itself become very difficult to read because of wrapping at some point).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/118)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[config/federation/prometheus/alerts.yml, line 52 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/118#-Kxy8lkH813kKRhkoqbQ:-KxyK_fzuK7k74W834ep:b-sau3hr) ([raw file](https://github.com/m-lab/prometheus-support/blob/21390d150e667c2c6202c03b94c78f0a5fd8ca3f/config/federation/prometheus/alerts.yml#L52)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

If you're feelings are strong on the matter, I'm fine with just going with your option two. I think I prefer an indent that resets instead of always increasing (that could itself become very difficult to read because of wrapping at some point).
</blockquote></details>

I agree that too many indents is cumbersome.

I don't think of it as 3 or 6 spaces, I'm really just trying to line things up visually to be easy to inspect.

My eyes have to hunt for the metric in most of these examples.

In the second option I proposed, all the metrics are aligned with one another and all the logical operations are aligned with one another. Of the four variations we've explored here I think that option is my favorite. Please use this one:

```
 IF sum_over_time(up{service="sidestream"}[10m]) == 0
       AND ON(machine)
    sum_over_time(probe_success{service="ssh806"}[20m]) / 20 >= 0.90
       UNLESS ON(machine)
    lame_duck_node == 1
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/118)*

**Comment by nkinkade** [comment]
I merged the master branch to this one before my last push.

PTAL?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/118#-:-KxyQi9mKaM6z8SGXW1Q:b-7fmyln)*

**Comment by stephen-soltesz** [comment]
:lgtm: -- Thank you!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/118#-:-KxyeUmlboFyIo6iUg7k:bspa67d)*

**Pull request merged**
