### PR TITLE
Adds a Cloud Build configuration file

### PR DESCRIPTION
**Pull request by nkinkade**
This PR adds a Cloud Build configuration file, allowing us to migrate away from Travis-CI to Cloud Build. 

My strategy for moving builds from Travis-CI to Cloud Build was to spend no time optimizing, and to as quickly as possible shoehorn the build into Cloud Build. My goal was to touch the various deployments script as little as possible, and only enough to get the build to work in Cloud Build. We can worry about optimizing and cleaning up the build later. I only touched build scripts where it was absolutely necessary, or where there was an obvious/easy fix for some deficiency.

The Travis-CI build relies on a startling number of environment variable injected into the build, which are stored as part of the repo in Travis. Some of those variables are no longer needed, as we can leverage the permissions of the Cloud Build service account to do many thing within a GCP project. However, a non-trivial number of secrets have to be manually collected and converted into Secret Manager secrets, and then integrated into the Cloud Build build. This has been done for mlab-sandbox, but still has not been done for mlab-staging and mlab-oti. I do now, however, now know which exact secrets are needed and how to find them, and have a small script to automate creation of the secrets in any given project.

`k8s/prometheus-federation/roles/cloud-build.yml`:
It was necessary to create this file with an RBAC ClusterRole and ClusterRoleBinding to avoid a build error when installing the nginx ingress controller via Helm. I don't fully understand why IAM permissions were not sufficient, but this article explains what I was running up against a little bit:

https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#permission_to_create_or_update_roles_and_role_bindings

That said, despite those RBAC configs, builds continued to fail, but with a new error, warning me that these IAM permissions were necessary:

* container.validatingWebhookConfigurations.update
* container.mutatingWebhookConfigurations.update

I manually added these to the `cloud-kubernetes-deployer` custom role. I also applied that custom role to the default Cloud Build service account. It's not clear why those IAM permissions were necessary, in addition to the RBAC configurations, but things seem to work now.

One other note is that I disabled bash command echoing in apply-global-prometheus.sh. Cloud Build doesn't handle secret data the same way as Travis, and sensitive data gets exposed in the build logs. Rather than trying to selectively turn command echoing on and off over and over throughout the file, I just disabled it altogether. The logs still seem useful.

The latest successful build, using the changes in the PR can be viewed here:

https://console.cloud.google.com/cloud-build/builds;region=global/6c58fe72-13be-4295-add2-4c9a863d6704?project=mlab-sandbox

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938)* status: 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`k8s/prometheus-federation/roles/cloud-build.yml` line 19 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9Dgc580I1Y4OUErNL9:-N9Do5xl6ZiagiMk2-Bw:b-otauxn) ([raw file](https://github.com/m-lab/prometheus-support/blob/f049cf35de5db9b36f82d6e2d0a7375795653f2e/k8s/prometheus-federation/roles/cloud-build.yml#L19)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This account is for mlab-sandbox ; we'll need to do the same for the CB account in staging & oti too..

Keeping this cluster role someplace in the repo for documentation is welcome. I would not object to keeping this role creation manual.
Or maybe it's always `${PROJECT_NUMBER}@cloudbuild.gserviceaccount.com`?
</blockquote></details>

A belated vote for making this automated if the SA name is this predictable. The reason being if we ever want to recreate the prometheus-federation cluster to a new more consistent name, i.e. "monitoring" cluster, it would be nice for that to be a single name change and all the settings available as code where possible. Or, even a third party deployment of similar components.

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: I've made various changes which I think should address your questions and concerns. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938#-:-N9IEsVfAFrfxhtHo-dO:bd43pby)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cloudbuild.yaml` line 121 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9DjDyIAcqqzSmTdd0B:-N9DmPNREReiGHW73E8r:bmawhvw) ([raw file](https://github.com/m-lab/prometheus-support/blob/f049cf35de5db9b36f82d6e2d0a7375795653f2e/cloudbuild.yaml#L121)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this zone the same across projects?
</blockquote></details>

Maybe not. Good catch. I forgot to make this a variable discovered at build time. This should be fixed now.
___
*[`cloudbuild.yaml` line 131 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9Dj5Dk11sxZiv2NK40:-N9DmZ5b4vdcq0t1MHe_:b-8hlqbe) ([raw file](https://github.com/m-lab/prometheus-support/blob/f049cf35de5db9b36f82d6e2d0a7375795653f2e/cloudbuild.yaml#L131)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are these regions the same across projects today?
</blockquote></details>

Maybe not. Good catch. I forgot to make this a variable discovered at build time. This should be fixed now. Note that the updated `gcloud` command uses the `--zone` flag, whether the cluster is zonal _or_ regional. It is counterintuitive, but it works just fine. And sure enough, if you describe a regional cluster (e.g., data-processing), you will see a "zone" of "us-east1"  in the cluster details.
___
*[`k8s/prometheus-federation/roles/cloud-build.yml` line 19 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9Dgc580I1Y4OUErNL9:-N9DmcrMDeFLk_yaa4OW:by3k59c) ([raw file](https://github.com/m-lab/prometheus-support/blob/f049cf35de5db9b36f82d6e2d0a7375795653f2e/k8s/prometheus-federation/roles/cloud-build.yml#L19)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

A belated vote for making this automated if the SA name is this predictable. The reason being if we ever want to recreate the prometheus-federation cluster to a new more consistent name, i.e. "monitoring" cluster, it would be nice for that to be a single name change and all the settings available as code where possible. Or, even a third party deployment of similar components.
</blockquote></details>

Good catch. I was concerned with getting things working in sandbox, and forgot to parameterize various configs. This should be done now.

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938)* status: 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`cloudbuild.yaml` line 98 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9IFySs4GC5YRrnxo4e:-N9IFySs4GC5YRrnxo4f:ba88r86) ([raw file](https://github.com/m-lab/prometheus-support/blob/da7137604b9f1b7b808ecaa27722c11ca5cfbf44/cloudbuild.yaml#L98)):*
> ```YAML
>       gcloud container clusters list --filter "name=${cluster}" \
>         --format="value(location)" \
>         --project mlab-sandbox
> ```

Project is static.
___
*[`README.md` line 135 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9IGBnU4MA7kJ5znAJn:-N9IGBnU4MA7kJ5znAJo:b-esk1z3) ([raw file](https://github.com/m-lab/prometheus-support/blob/da7137604b9f1b7b808ecaa27722c11ca5cfbf44/README.md#L135)):*
> ```Markdown
> default Cloud Build service account cannot deploy the cluster without having
> certain RBAC permissions assigned to it in the cluster in advance, before
> `apply-global-prometheus.sh` gets run for the first time. In order to apply
> ```

s/gets run/runs/
___
*[`README.md` line 139 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9IGfOa3O8UeaQQ0bif:-N9IGfOb4dHB2w5viYLm:boa6pf6) ([raw file](https://github.com/m-lab/prometheus-support/blob/da7137604b9f1b7b808ecaa27722c11ca5cfbf44/README.md#L139)):*
> ```Markdown
> 
> ```
> ./bootstrap-prometheus-federation.sh <cluster project> <cluster zone or region>
> ```

Did you also mean to add this script to this PR?

**Review by nkinkade — COMMENTED** [review]
PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938#-:-N9Ia-xn5vi4Nt42kRc_:b-833305)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cloudbuild.yaml` line 98 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9IFySs4GC5YRrnxo4e:-N9I_RSk4oyGsnV06b7W:bacue8p) ([raw file](https://github.com/m-lab/prometheus-support/blob/da7137604b9f1b7b808ecaa27722c11ca5cfbf44/cloudbuild.yaml#L98)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Project is static.
</blockquote></details>

Thank you for catching that. Fixed.
___
*[`README.md` line 135 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9IGBnU4MA7kJ5znAJn:-N9I__kbAXT4-o5w4a3Q:b-896fix) ([raw file](https://github.com/m-lab/prometheus-support/blob/da7137604b9f1b7b808ecaa27722c11ca5cfbf44/README.md#L135)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/gets run/runs/
</blockquote></details>

Done.
___
*[`README.md` line 139 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9IGfOa3O8UeaQQ0bif:-N9I_vJaB6oHJ5Nw0MAM:b-fkfujl) ([raw file](https://github.com/m-lab/prometheus-support/blob/da7137604b9f1b7b808ecaa27722c11ca5cfbf44/README.md#L139)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Did you also mean to add this script to this PR?
</blockquote></details>

Yes, I did! I was sure I had `git add`ed it, but apparently not. Thank you for noticing that.

**Review by stephen-soltesz — APPROVED** [review]
One suggestion and one clarifying question. :lgtm:

> Reviewed 1 of 4 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938#-:-N9IcY1s6OJ7GYCi8uEf:banjosk)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[`bootstrap-prometheus-federation.sh` line 29 at r3](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9Ic8lQ-2OElF1DUw-L:-N9Ic8lR2YLNxcEI_Nxj:b-m9kkyz) ([raw file](https://github.com/m-lab/prometheus-support/blob/f8e4457da3224315e69cd96f08e140e91cab020b/bootstrap-prometheus-federation.sh#L29)):*
> ```Shell
> sed -e 's|{{PROJECT_NUMBER}}|'$project_number'|g' \
>   k8s/prometheus-federation/roles/cloud-build.yml.template > \
>   k8s/prometheus-federation/roles/cloud-build.yml
> ```

So this file isn't accidentally applied to the cluster from a local filesystem, I suggest naming the file with the project, e.g. `cloud-build.yml.$project` -- the apply command doesn't care what the file name is and masking the .yml extension could prevent a simple accident.
___
*[`cloudbuild.yaml` line 98 at r3](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9IanWR01V7-eHigBsY:-N9IanWR01V7-eHigBsZ:bpp8t7k) ([raw file](https://github.com/m-lab/prometheus-support/blob/f8e4457da3224315e69cd96f08e140e91cab020b/cloudbuild.yaml#L98)):*
> ```YAML
>       gcloud container clusters list --filter "name=${cluster}" \
>         --format="value(location)" \
>         --project $PROJECT
> ```

Under what conditions is `$$` needed vs `$` ?

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`bootstrap-prometheus-federation.sh` line 29 at r3](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9Ic8lQ-2OElF1DUw-L:-N9IjWUaAGi-hK-lEH22:b60qxd5) ([raw file](https://github.com/m-lab/prometheus-support/blob/f8e4457da3224315e69cd96f08e140e91cab020b/bootstrap-prometheus-federation.sh#L29)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

So this file isn't accidentally applied to the cluster from a local filesystem, I suggest naming the file with the project, e.g. `cloud-build.yml.$project` -- the apply command doesn't care what the file name is and masking the .yml extension could prevent a simple accident.
</blockquote></details>

I'm sorry, could you clarify this request? I named the RBAC file with a `.template` suffix precisely for this reason, such that it won't as easily be confused as a regular YAML file that could or should be applied without having first evaluating the template.  Should the script clean up the `.yml` file after the template has been evaluated and applied to the cluster?

Adding a project suffix the file means that we would need 3 of those files, one for each project, which far less flexible than a single template that can be modified at deploy time for the appropriate project. 
___
*[`cloudbuild.yaml` line 98 at r3](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9IanWR01V7-eHigBsY:-N9Ij1KuD7MrXR8HSS7l:b-n5hnjo) ([raw file](https://github.com/m-lab/prometheus-support/blob/f8e4457da3224315e69cd96f08e140e91cab020b/cloudbuild.yaml#L98)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Under what conditions is `$$` needed vs `$` ?
</blockquote></details>

Cloud Build does variable substitution in config files before it launches the build. It looks for variables like `$<string>` to substitute, and will complain and fail if the variable doesn't exist. To prevent Cloud Build from trying to interpret a shell variable in a script a as substitution variable, you use the `$$` syntax. It is just a way of escaping the shell variable.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[`bootstrap-prometheus-federation.sh` line 29 at r3](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9Ic8lQ-2OElF1DUw-L:-N9IkbkF25UOlUSdO34f:b-sh5mck) ([raw file](https://github.com/m-lab/prometheus-support/blob/f8e4457da3224315e69cd96f08e140e91cab020b/bootstrap-prometheus-federation.sh#L29)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I'm sorry, could you clarify this request? I named the RBAC file with a `.template` suffix precisely for this reason, such that it won't as easily be confused as a regular YAML file that could or should be applied without having first evaluating the template.  Should the script clean up the `.yml` file after the template has been evaluated and applied to the cluster?

Adding a project suffix the file means that we would need 3 of those files, one for each project, which far less flexible than a single template that can be modified at deploy time for the appropriate project. 
</blockquote></details>

Sorry - I was only referring to the output filename. Since this script is meant to be run locally, the current output creates a name that's indistinguishable from other .yml files under the k8s/** directory. The project suffix just tries to prevent that. Removing the file after would also do that. Either would be okay.
___
*[`cloudbuild.yaml` line 98 at r3](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9IanWR01V7-eHigBsY:-N9Il9ss-TMy0bklc891:b-wsa5so) ([raw file](https://github.com/m-lab/prometheus-support/blob/f8e4457da3224315e69cd96f08e140e91cab020b/cloudbuild.yaml#L98)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Cloud Build does variable substitution in config files before it launches the build. It looks for variables like `$<string>` to substitute, and will complain and fail if the variable doesn't exist. To prevent Cloud Build from trying to interpret a shell variable in a script a as substitution variable, you use the `$$` syntax. It is just a way of escaping the shell variable.
</blockquote></details>

Does that not apply to `$PROJECT` here? Or, `$1` for that matter. Everywhere else I see `$$PROJECT`. Presumably this works as intended, but I don't understand why :)

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`bootstrap-prometheus-federation.sh` line 29 at r3](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9Ic8lQ-2OElF1DUw-L:-N9J9zI51zsLmI2F0ovY:b-rnc0i4) ([raw file](https://github.com/m-lab/prometheus-support/blob/f8e4457da3224315e69cd96f08e140e91cab020b/bootstrap-prometheus-federation.sh#L29)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Sorry - I was only referring to the output filename. Since this script is meant to be run locally, the current output creates a name that's indistinguishable from other .yml files under the k8s/** directory. The project suffix just tries to prevent that. Removing the file after would also do that. Either would be okay.
</blockquote></details>

I updated the script to remove the evaluated template .yml  file after it has been applied to the cluster.
___
*[`cloudbuild.yaml` line 98 at r3](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9IanWR01V7-eHigBsY:-N9J8ZAN4oVmRWeyZAsN:b8hvqlz) ([raw file](https://github.com/m-lab/prometheus-support/blob/f8e4457da3224315e69cd96f08e140e91cab020b/cloudbuild.yaml#L98)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does that not apply to `$PROJECT` here? Or, `$1` for that matter. Everywhere else I see `$$PROJECT`. Presumably this works as intended, but I don't understand why :) 
</blockquote></details>

We chatted about this on the Open VC, but to summarize here, it appears that Cloud Build will only try to interpret variables in the build config if they match either one of these regular expressions: `[A-Z0-9_]+`, `_[A-Z0-9_]+`. If they don't, then Cloud Build will ignore them. Additionally, while [bash parameter expansion](https://cloud.google.com/build/docs/configuring-builds/use-bash-and-bindings-in-substitutions#bash_parameter_expansions) _is_ supported by Cloud Build, a careful reading of the documentation seems to indicate that it is _only_ supported when defining substitutions for a build trigger, and not generally throughout a build config.  So, Cloud Build would ignore something like `${PROJECT/-/_}` in a build config. However, to make usage of `$` and `$$` consistent throughout the build config, wherever parameter substitution is done, I use the syntax `$${PROJECT/-/_}` (double dollar sign). Even though Cloud Build would have ignored the single `$` usage, it does the right thing, too, when there are two `$$`.

I also added a note to the top of the build config about this convention.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938#-:-N9M9Gg-9AQOcIgw95kn:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[`cloudbuild.yaml` line 98 at r3](https://reviewable.io/reviews/m-lab/prometheus-support/938#-N9IanWR01V7-eHigBsY:-N9M8_OKEVSu4SAqPgSM:bsp4o74) ([raw file](https://github.com/m-lab/prometheus-support/blob/f8e4457da3224315e69cd96f08e140e91cab020b/cloudbuild.yaml#L98)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

We chatted about this on the Open VC, but to summarize here, it appears that Cloud Build will only try to interpret variables in the build config if they match either one of these regular expressions: `[A-Z0-9_]+`, `_[A-Z0-9_]+`. If they don't, then Cloud Build will ignore them. Additionally, while [bash parameter expansion](https://cloud.google.com/build/docs/configuring-builds/use-bash-and-bindings-in-substitutions#bash_parameter_expansions) _is_ supported by Cloud Build, a careful reading of the documentation seems to indicate that it is _only_ supported when defining substitutions for a build trigger, and not generally throughout a build config.  So, Cloud Build would ignore something like `${PROJECT/-/_}` in a build config. However, to make usage of `$` and `$$` consistent throughout the build config, wherever parameter substitution is done, I use the syntax `$${PROJECT/-/_}` (double dollar sign). Even though Cloud Build would have ignored the single `$` usage, it does the right thing, too, when there are two `$$`.

I also added a note to the top of the build config about this convention.
</blockquote></details>

Thank you for the summary and the description at the top.

Looking forward, what would be a helpful way to iterate toward something more like a canonical cloudbuild deployment (vs a forklifted shell script)? What is the end state we would prefer ultimately that this is an iterative step toward?

**Comment by stephen-soltesz** [comment]
Please let me know before you merge this. We want to update the secrets for oauth to work with the github provider.

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: Per our conversation on the Open VC, I have added additional commits to this PR:

* Installs `jsonlint-php` to lint provisioned Grafana dashboard files. I'm using jsonlint-php, since that was available through the package manager, with no need to mess around with `npm`.
* Removes the `.travis.yml` configuration file. When I did this, Travis did not appear to generate a build when I pushed, with no other action like disabling builds for the repo at travis-ci.com.
* Removes the `travis` git submodule.
* I update the oauth2-proxy related secrets in Secret Manager to the ones you specified for the Github provider. This isn't a commit, but just a noteworthy change.

PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938#-:-N9n4VlpE-GX4MkUvKrD:bv9wor)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
Quick note: please add a note to the README about updating secrets.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938#-:-N9qOQfo9-kJUT8rNzp8:b-kzwqqe)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — APPROVED** [review]
New changes look good to me.

Please add a note to the README for updating secrets.
Please confirm that the sandbox oauth secrets are up to date. This morning it was out of order.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938#-:-N9qy_Sv56Fl0qwSrPiM:b-9y7lz1)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: I added a new section to the README about updating secret values in Secret Manager. PTAL?

The sandbox OAuth2 logins were broken because I had pushed to sandbox yesterday, overwriting your changes. I rebased my branch (sandbox-kinkade) on main, and pushed again, and now auth seems to WAI. Could you verify?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938#-:-N9rkIP-CLXManQ-CADB:b50dajy)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/938#-:-N9rnbJ7-oFORzqhGjqS:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
