### PR TITLE
Update bq exporter queries to use the v2 switch datatype

### PR DESCRIPTION
**Pull request by robertodauria**
This PR updates the bigquery exporter queries to refer to the v2 switch tables and to use the new schema.

Note: I won't merge this until 1. the v2 switch datatype parser is merged and 2. the views referenced in this PR have been created (through a separate PR to etl-schema).

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/880)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
Sorry, I missed this yesterday - two nits.

:lgtm: with the changes.

I think you know this already - this change is blocked on other deployments.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/880#-:-Mwi68Sk-g7RdJmQHaxe:b8c6cr6)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @robertodauria)

___
*[config/federation/bigquery/bq_gardener_parse_time.sql.template, line 26 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/880#-Mwi5bsL37yncO0q2WSM:-Mwi5bsL37yncO0q2WSN:b6j3zzz) ([raw file](https://github.com/m-lab/prometheus-support/blob/dda3a68dde932f2bdac57cb89cc8b134441d2e3a/config/federation/bigquery/bq_gardener_parse_time.sql.template#L26)):*
> ```
>     FROM   `{{PROJECT}}.sidestream.web100_legacy`
>   UNION ALL
>     SELECT "utilization/switch" AS datatype, MIN(Parser.Time) AS min_parse_time
> ```

I guess while I'm here, (I see that other changes do this too), I think it's preferable to use the underlying bigquery field name capitalization even if bq is not case sensitive. So, `parser.Time` here.
___
*[config/federation/bigquery/bq_ndt_s2c.sql, line 24 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/880#-Mwi5PKU2MqvvVqPmNcP:-Mwi5PKU2MqvvVqPmNcQ:b-t4q7gt) ([raw file](https://github.com/m-lab/prometheus-support/blob/dda3a68dde932f2bdac57cb89cc8b134441d2e3a/config/federation/bigquery/bq_ndt_s2c.sql#L24)):*
> ```TSQL
>     CONCAT(a.Machine, "-", a.Site) AS node,
>     TIMESTAMP_SUB(a.CollectionTime, INTERVAL 10 SECOND) AS tstart,
>     a.collectionTime AS tend,
> ```

nit: please use `a.CollectionTime` (capital). I guess BQ is not case sensitive, but I think it's clearer if we use the underlying field name as-is.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/880)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/federation/bigquery/bq_gardener_parse_time.sql.template, line 26 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/880#-Mwi5bsL37yncO0q2WSM:-MxA-Zcf0Xovnpi41tZs:b-896fix) ([raw file](https://github.com/m-lab/prometheus-support/blob/dda3a68dde932f2bdac57cb89cc8b134441d2e3a/config/federation/bigquery/bq_gardener_parse_time.sql.template#L26)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I guess while I'm here, (I see that other changes do this too), I think it's preferable to use the underlying bigquery field name capitalization even if bq is not case sensitive. So, `parser.Time` here.
</blockquote></details>

Done.

**Review by stephen-soltesz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/880)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @robertodauria and @stephen-soltesz)

___
*[config/federation/bigquery/bq_ndt_s2c.sql, line 19 at r3](https://reviewable.io/reviews/m-lab/prometheus-support/880#-MxGXHY33oRYm41wAcEa:-MxGXHY33oRYm41wAcEb:bges7i7) ([raw file](https://github.com/m-lab/prometheus-support/blob/60fb60b1a0694834e5349fe34b6d0d149e6ba211/config/federation/bigquery/bq_ndt_s2c.sql#L19)):*
> ```TSQL
> CREATE TEMPORARY FUNCTION
>   toNodeName(tfn STRING) AS ( CONCAT( REGEXP_EXTRACT(tfn, r'(mlab[1-4])-[a-z]{3}[0-9]{2}.*'), "-", REGEXP_EXTRACT(tfn, r'mlab[1-4]-([a-z]{3}[0-9]{2}).*') ) );
> WITH
> ```

If we move this file to a later PR, the rest of this PR could be merged now, and follow the parser & gardener through to production.

As second release of etl-schema followed by a PR that adds this PR could complete the sequence, I think.

How does that sound?

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/880)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/federation/bigquery/bq_ndt_s2c.sql, line 19 at r3](https://reviewable.io/reviews/m-lab/prometheus-support/880#-MxGXHY33oRYm41wAcEa:-MxGlv1ODDy-vNVHIK5u:boyexb3) ([raw file](https://github.com/m-lab/prometheus-support/blob/60fb60b1a0694834e5349fe34b6d0d149e6ba211/config/federation/bigquery/bq_ndt_s2c.sql#L19)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If we move this file to a later PR, the rest of this PR could be merged now, and follow the parser & gardener through to production.

As second release of etl-schema followed by a PR that adds this PR could complete the sequence, I think.

How does that sound?
</blockquote></details>

Done. Thanks!

**Pull request merged**
