### PR TITLE
Add PDF comparisons for Early Exit dashboard

### PR DESCRIPTION
**Pull request by cristinaleonr**
- [Download speed](https://grafana.mlab-sandbox.measurementlab.net/d/W8JPPzzIz/ndt-early-exit?orgId=1&viewPanel=14)
- [Bytes sent](https://grafana.mlab-sandbox.measurementlab.net/d/W8JPPzzIz/ndt-early-exit?orgId=1&viewPanel=13)

This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1012)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
nit: for axis labels

Rather than "Test Count" say "Frequency" or "Test Frequency" on the y-axis (or omit). I suggest simplifying the x-axis to simply "Mbps".

Similarly for the Bytes sent panel; I suggest a similar update to the y-axis and "Test size (bytes)" for the x-axis.

For both panels I suggest adding "Normalized" to the title.

This is very cool!

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1012#-:-NeFJSRl5OLkuRAN2YM7:b-4jk9pc)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
Follow up nit: please revise the "Script" variable names to match or be generic to the use case. It's confusing to use "site" when you're only grouping by a generic label.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1012#-:-NeFLPWZDkWuD48l3U8d:b-3fa18z)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by cristinaleonr — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1012#-:-NeFO9Yg1oT6k2LtkFhL:b-896fix)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
I'm realizing that technically the unit on the bytes sent panel is "MB".

**Pull request merged**
