### PR TITLE
Add wiki entry for Cloud_TooManyAppEngineVersions alert

### PR DESCRIPTION
**Pull request by stephen-soltesz**
After the Cloud_TooManyAppEngineVersions fired in staging, I created https://github.com/m-lab/etl/pull/1042 to help do this automatically. This is also a good time to update the description to reference the Alerts and troubleshooting wiki.

@SaiedKazemi what additional information would be helpful here or in the wiki?

@nkinkade also does this look right to you?

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/859)

### CODE REVIEW

**Review by nkinkade — APPROVED** [review]
:lgtm: The ops-tracker wiki entry references mlab-sandbox for the AppEngine console link. It should probably reference mlab-oti instead. Thanks for growing the "playbook" wiki!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/859#-:-MrcXAr47H8sfBC4t809:b51i740)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

**Review by stephen-soltesz — COMMENTED** [review]
Thank you. Fixed the reference to mlab-oti.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/859#-:-MrcZI7u3pVwn8NVdrla:baezeyg)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

**Comment by SaiedKazemi** [comment]
___
*[config/federation/prometheus/alerts.yml, line 969 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/859#-Ms4uvzXAjJwyUPa6aF-:-Ms4uvzXAjJwyUPa6aF0:b-7nt5sz) ([raw file](https://github.com/m-lab/prometheus-support/blob/02ac49c9d0da41552a08d90e20fba85aae973537/config/federation/prometheus/alerts.yml#L969)):*
> ```YAML
>     annotations:
>       summary: Too many AppEngine versions for the project.
>       description: https://github.com/m-lab/ops-tracker/wiki/Alerts-&-Troubleshooting#cloud_toomanyappengineversions
> ```

Looking at the contents of this link, I have two comments under `Troubleshooting`:

1. It seems to me that the second bullet should be a part of the first bullet or a sub-bullet of it.
2. I think the third bullet will be more clear if it read: `... includes a garbage collection script called delete-appengine.sh .... Run this script manually to remove old service versions.`

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/859)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[config/federation/prometheus/alerts.yml, line 969 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/859#-Ms4uvzXAjJwyUPa6aF-:-Ms_rnKX4yVOuuvlsBpj:b-wn9nc5) ([raw file](https://github.com/m-lab/prometheus-support/blob/02ac49c9d0da41552a08d90e20fba85aae973537/config/federation/prometheus/alerts.yml#L969)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Looking at the contents of this link, I have two comments under `Troubleshooting`:

1. It seems to me that the second bullet should be a part of the first bullet or a sub-bullet of it.
2. I think the third bullet will be more clear if it read: `... includes a garbage collection script called delete-appengine.sh .... Run this script manually to remove old service versions.`
</blockquote></details>

Thank you, I've updated the entry. PTAL?

**Comment by stephen-soltesz** [comment]
I believe @SaiedKazemi will be OOO - so I'll merge this TBR if he has more feedback.

**Comment by SaiedKazemi** [comment]
___
*[config/federation/prometheus/alerts.yml, line 969 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/859#-Ms4uvzXAjJwyUPa6aF-:-Msb7ubf3GULu5Zlu6qi:b-sz0g3c) ([raw file](https://github.com/m-lab/prometheus-support/blob/02ac49c9d0da41552a08d90e20fba85aae973537/config/federation/prometheus/alerts.yml#L969)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you, I've updated the entry. PTAL?
</blockquote></details>

Looks good.  Thanks for the changes.



_Code quote:_
```YAML
https://github.com/m-lab/ops-tracker/wiki/Alerts-&-Troubleshooting#cloud_toomanyappengineversions
```

**Pull request merged**
