### PR TITLE
Configuration for Prometheus in Kubernetes

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This PR adds a Dockerfile and Prometheus configuration for M-Lab monitoring.

This configuration should be deployed within a kubernetes cluster. The kubernetes API server, nodes in the kubernetes cluster, as well as other pods and services running in the cluster are automatically discovered and added as targets for monitoring by Prometheus.

This configuration also supports file based service discovery. This will allow us to update the list of monitored legacy targets at run-time by copying a configuration file into the container.

This PR also adds instructions in the README.md for building and deploying the demo prometheus image.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1)

### CODE REVIEW

**Comment by nkinkade** [comment]
I added a few comments... half just typo corrections. :) It's hard for me to give a good review of this without knowing more about Prometheus and Kubernetes, which will come in time. In other words, do not consider this a formal review (from me) of your method and exact syntax.

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[prometheus.yml, line 58 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbWC7mLUfDenGeJs9QZ:-KbWC7mLUfDenGeJs9Q_:bd6pkr2) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/prometheus.yml#L58)):*
> ```YAML
>   #
>   # The separation allows each component to use different authentication
>   # configs, or apply different relabling rules.
> ```

s/relabling/relabeling/

---

*[prometheus.yml, line 64 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbWCGRQqkdyw9R2Gr3z:-KbWCGRQqkdyw9R2Gr4-:bjsjat) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/prometheus.yml#L64)):*
> ```YAML
>   # The kubernetes API is exposed as an "endpoint". Since kubernetes may have
>   # many endpoints, this configuration restricts the targets monitored to the
>   # default/kubernetes service. The relabelling rules ignore other endpoints.
> ```

s/relabelling/relabeling/

---

*[prometheus.yml, line 78 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbWCiQ4fRnl4U46YSrp:-KbWCiQ4fRnl4U46YSrq:b-7em898) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/prometheus.yml#L78)):*
> ```YAML
>     bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
> 
>     # The source_labels are concatenated with ';'. The regex matches a single
> ```

Are the `source_labels` concatenated with semicolons, or the regexes?

---

*[README.md, line 28 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbWAGaa6GX8YUKyCDy9:-KbWAGabjSB8v_GDMd7y:bsx5w2d) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/README.md#L28)):*
> ```Markdown
> 
>     kubectl run demo-prometheus --image=<username>/demo-prometheus --port=9090
>     kubectl expose deployment demo-prometheus --type="LoadBalancer"
> ```

Is `--type="LoadBalancer"` necessary, or just a why-not sort of thing? 

---

*[README.md, line 32 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbW9HxNncuRFoFfv9NN:-KbW9HxNncuRFoFfv9NO:b-v4rnpe) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/README.md#L32)):*
> ```Markdown
>     sleep 60 && kubectl get service demo-prometheus
> 
> After a minute or two, `kubectl get service demo-prometheus` shold report the
> ```

s/shold/should/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-:-KbWED55sNZMAMO48LSO:bepcrcd)*

**Comment by stephen-soltesz** [comment]
Yeah, I understand. I don't think anyone has enough experience yet (even me). But, I hope this review could be an opportunity to dive in and learn a little more.

---

Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[prometheus.yml, line 58 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbWC7mLUfDenGeJs9QZ:-KbWPxmATNN6uGkKy-Is:b-896fix) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/prometheus.yml#L58)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

s/relabling/relabeling/
</blockquote></details>

Done.

---

*[prometheus.yml, line 64 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbWCGRQqkdyw9R2Gr3z:-KbWQ4pwsK_CSUfckrDF:b-896fix) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/prometheus.yml#L64)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

s/relabelling/relabeling/
</blockquote></details>

Done.

---

*[prometheus.yml, line 78 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbWCiQ4fRnl4U46YSrp:-KbWQHV7TigFPWUEOZvC:beowl6v) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/prometheus.yml#L78)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Are the `source_labels` concatenated with semicolons, or the regexes?
</blockquote></details>

The `source_labels` are concatenated with semicolons (the default separator character), and the string that results from the concatenation (which now includes the semicolons) is matched against the regex.

See also: https://prometheus.io/docs/operating/configuration/#relabel_config

---

*[README.md, line 28 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbWAGaa6GX8YUKyCDy9:-KbWSVj8hCujh2S37tGN:b-p1tfhc) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/README.md#L28)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is `--type="LoadBalancer"` necessary, or just a why-not sort of thing? 
</blockquote></details>

The default type is ClusterIP (https://kubernetes.io/docs/user-guide/kubectl/kubectl_expose/) which doesn't work (just checked). So this flag is necessary to get a public IP allocated.

I took this flag from the quickstart example. And, I honestly don't fully understand the difference between the types (ClusterIP, NodePort, LoadBalancer). The public docs are overly terse, almost placeholders more than docs.

---

*[README.md, line 32 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbW9HxNncuRFoFfv9NN:-KbWRH6gPEUoa8Raxwqy:b-896fix) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/README.md#L32)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

s/shold/should/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-:-KbWTfs3DOROdgAMKP0v:btrq5qc)*

**Comment by pboothe** [comment]
*[deploy.sh, line 7 at r3](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbWY16H1EwR6EUVOUs-:-KbWY16H1EwR6EUVOUs0:bsamnci) ([raw file](https://github.com/m-lab/prometheus-support/blob/775ae3e9f57916be26cab555634a609098994f14/deploy.sh#L7)):*
> ```Shell
> kubectl expose deployment prometheus --type="LoadBalancer"
> kubectl annotate services prometheus prometheus.io/scrape=true
> sleep 60 && kubectl get service prometheus
> ```

Put an echo right before the sleep to explain that it's about to sleep for 60s to wait for the service to be up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/1)*

**Comment by stephen-soltesz** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[deploy.sh, line 7 at r3](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbWY16H1EwR6EUVOUs-:-KbWZGnZ3CkiSOBG4S01:b-k4ashy) ([raw file](https://github.com/m-lab/prometheus-support/blob/775ae3e9f57916be26cab555634a609098994f14/deploy.sh#L7)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Put an echo right before the sleep to explain that it's about to sleep for 60s to wait for the service to be up.
</blockquote></details>

Whoops! This script was added accidentally. I only meant to have these commands once as examples in the README. 

I've corrected the github history for the last commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/1)*

**Comment by pboothe** [comment]
*[README.md, line 28 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbWAGaa6GX8YUKyCDy9:-KbWZZQ_etAqVHeHAZoq:byou1y9) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/README.md#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The default type is ClusterIP (https://kubernetes.io/docs/user-guide/kubectl/kubectl_expose/) which doesn't work (just checked). So this flag is necessary to get a public IP allocated.

I took this flag from the quickstart example. And, I honestly don't fully understand the difference between the types (ClusterIP, NodePort, LoadBalancer). The public docs are overly terse, almost placeholders more than docs.
</blockquote></details>

https://kubernetes.io/docs/user-guide/services/#publishing-services---service-types is the best I have found, and it makes it sound like LoadBalancer is the right choice when you want Kubernetes and cloud hosting to set up as much as possible for you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/1)*

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-:-KbXENF8NgmP7K093D7o:bnfp4nl)*

**Comment by salarcon215** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 20 at r4](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbvLxwwF8waouU8-Anu:-KbvLlNr4iG6szOc6QTB:bv3pghl) ([raw file](https://github.com/m-lab/prometheus-support/blob/ff5478863981556f4e528cda4f8ae72aef10917a/README.md#L20)):*
> ```Markdown
>     sudo docker login
>     sudo docker build -t demo-prometheus .
>     sudo docker tag demo-prometheus <username>/demo-prometheus:latest
> ```

To the brand new beginner working in Google Cloud Shell, there's a moment of hesitation about whether <username> here is username in the shell (to create something in a new local directory) or Dockerhub username. Would it muck up the file to say <dockerhub-username> or <dockerhub-id>?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/1)*

**Comment by stephen-soltesz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 28 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbWAGaa6GX8YUKyCDy9:-Kbv_3KkSTAl0p_OZ0Lr:b27ybfo) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/README.md#L28)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

https://kubernetes.io/docs/user-guide/services/#publishing-services---service-types is the best I have found, and it makes it sound like LoadBalancer is the right choice when you want Kubernetes and cloud hosting to set up as much as possible for you.
</blockquote></details>

Oh okay. These notes in the glossary are actually very helpful. They structured their documentation differently than what I expected.

---

*[README.md, line 20 at r4](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-KbvLxwwF8waouU8-Anu:-KbvZnwu3ZaQm67duWW0:b-brnubi) ([raw file](https://github.com/m-lab/prometheus-support/blob/ff5478863981556f4e528cda4f8ae72aef10917a/README.md#L20)):*
<details><summary><i>Previously, salarcon215 wrote…</i></summary><blockquote>

To the brand new beginner working in Google Cloud Shell, there's a moment of hesitation about whether <username> here is username in the shell (to create something in a new local directory) or Dockerhub username. Would it muck up the file to say <dockerhub-username> or <dockerhub-id>?
</blockquote></details>

Thank you, I added some clarifying text to make the dockerhub username more explicit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/1)*

**Comment by stephen-soltesz** [comment]
@salarcon215 I added some clarifying notes to the README and an example JSON file with a legacy target.

PTAL?

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-:-Kbvc2QBTuMKVtYqyr3Y:bekcvgd)*

**Comment by salarcon215** [comment]
LGTM. 

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 48 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-Kbvjkb8y3GDMwgHnjOk:-Kbvjkb8y3GDMwgHnjOl:b-42f6r8) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/README.md#L48)):*
> ```Markdown
> Using the file service discovery configuration, we can add new targets at
> runtime. Create a JSON or YAML input file in the [correct form][file_sd_config].
> ```

I see your sample in the readme in your Github repo, though it's not loading here. I explicitly thumbs-up the additions in your repo, which I'm stating so that when I give my LGTM you know that I'm responding to the latest and greatest, not the version I see here with isn't updating when I reload for reasons I won't speculate about.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-:-KbvkEP7PZ9OIt8iAk-q:bvdsyln)*

**Comment by stephen-soltesz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 48 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/1#-Kbvjkb8y3GDMwgHnjOk:-KbvlDF2OSDgXTRSdN_D:bvk521c) ([raw file](https://github.com/m-lab/prometheus-support/blob/03fb2849d6f3c1b4c28c98a4d1bbb32e93f137d3/README.md#L48)):*
<details><summary><i>Previously, salarcon215 wrote…</i></summary><blockquote>

I see your sample in the readme in your Github repo, though it's not loading here. I explicitly thumbs-up the additions in your repo, which I'm stating so that when I give my LGTM you know that I'm responding to the latest and greatest, not the version I see here with isn't updating when I reload for reasons I won't speculate about.
</blockquote></details>

Thank you.

Sometimes (for reasons unknown) I have to play with the revisions shown in the diffs using the "file matrix" interface at the top of this page. If you make the right end for README.md overlap with the last revision (r5) you should see the latest changes here. I don't know why it doesn't update to the last revision automatically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/1)*

**Pull request merged**
