### PR TITLE
Split uplink and speed labels on snmp metrics.

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change will re-label snmp metrics whose ifAlias label is in the form `uplink-<speed>`.

This will allow us to identify 1g vs 10g sites in monitoring and dashboards and alert appropriately.

The rule should have no effect on ifAlias values that do not start with "uplink". The rule should also have no effect on existing ifAlias values of only "uplink".

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/151)

### CODE REVIEW

**Comment by nkinkade** [comment]
One comment about possibly extending this PR.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[config/federation/prometheus/prometheus.yml.template, line 427 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/151#-L0MIbWvcdwXXeOlFpIE:-L0MIbWvcdwXXeOlFpIF:bnvcrpw) ([raw file](https://github.com/m-lab/prometheus-support/blob/0b209af660ffbbbd59f74833fbbc0361b24ac3ec/config/federation/prometheus/prometheus.yml.template#L427)):*
> ```
>     metric_relabel_configs:
> 
>       # 'ifAlias' labels use the format "uplink-<speed>" where speed is one of
> ```

Is now a good time to go ahead and prepare for having node interfaces labeled too? If so, we'll not only have ifAliases of the form "uplink-.*", but also "mlab[1-4]".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/151#-:-L0MJ1-g9WMJSs-kYcJ-:b-e89sye)*

**Comment by nkinkade** [comment]
But other LGTM.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/151#-:-L0MJA9apRBdV4zfLc-H:b46nvk6)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[config/federation/prometheus/prometheus.yml.template, line 427 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/151#-L0MIbWvcdwXXeOlFpIE:-L0MJZ8ZG1LItOP4QNoC:b-v8r3u4) ([raw file](https://github.com/m-lab/prometheus-support/blob/0b209af660ffbbbd59f74833fbbc0361b24ac3ec/config/federation/prometheus/prometheus.yml.template#L427)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is now a good time to go ahead and prepare for having node interfaces labeled too? If so, we'll not only have ifAliases of the form "uplink-.*", but also "mlab[1-4]".
</blockquote></details>

Yes, exactly. My expectation / understanding (but it's been a while) is that in that case the regex's will fail to match and the relabel rules will stop being evaluated. So, the ifAlias machine names will be preserved as-is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/151)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/151#-:-L0MJsBFgIIHuKfwRw4V:bnfp4nl)*

**Pull request merged**
