### PR TITLE
Add prometheus-bigquery-exporter deployment

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds configuration for the prometheus-bigquery-exporter to the prometheus-federation cluster.

With this change, pre defined bigquery queries  from `config/federation/bigquery` are loaded into a k8s configmap. The configmap is mounted by the `bigquery-exporter.yml` deployment so that the SQL files are available as local paths in the exporter arguments.

This change includes Legacy and Standard SQL versions of two queries. For example:
 * bq_ndt_test2.sql -- legacy sql.
 * bq_ndt_test.sql -- standard sql

The legacy sql form will be retired as soon as the prometheus-bigquery-exporter supports standard sql.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/120)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
@gfr10598 please review the queries under `config/federation/bigquery`.

@nkinkade please review the k8s configurations.

**Comment by gfr10598** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[apply-global-prometheus.sh, line 108 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH36XUuE0Cs_bMs23r:-KyH36XVtPr5z8NofOxT:b-203ulv) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/apply-global-prometheus.sh#L108)):*
> ```Shell
> kubectl create configmap bigquery-exporter-config \
>     --from-file=config/federation/bigquery \
>     --dry-run -o json | kubectl apply -f -
> ```

Just curious - why the dry-run and pipe?  Can't do this directly?

---

*[config/federation/bigquery/bq_ndt_tests.sql, line 1 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH3PWMGR4KpYoxTi1m:-KyH3PWMGR4KpYoxTi1n:b-s3p60x) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/config/federation/bigquery/bq_ndt_tests.sql#L1)):*
> ```SQLPL
> SELECT
> ```

Consider adding #standardSQL.  This both makes it obvious when reading, and serves as pragma to the query processor.

Add a short header comment?

Also, bq_ndt_test_counts.sql ?

---

*[config/federation/bigquery/bq_ndt_tests.sql, line 3 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH1yAFF0m3xIQSwv47:-KyH1yAFF0m3xIQSwv48:b-kxsslr) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/config/federation/bigquery/bq_ndt_tests.sql#L3)):*
> ```SQLPL
> SELECT
>   CASE connection_spec.data_direction
>     WHEN 0 THEN "c2s"
> ```

It is also easy to pull this out of the test_id with a regular expression.  Maybe preferable, since you are already using regexp below.

---

*[config/federation/bigquery/bq_ndt_tests.sql, line 24 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH2ma44m7TZvDDJN0f:-KyH2ma44m7TZvDDJN0g:b7irptl) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/config/federation/bigquery/bq_ndt_tests.sql#L24)):*
> ```SQLPL
>     -- Count all tests with in a REFRESH_RATE_SEC interval 36 hours ago.
>     UNIX_SECONDS(log_time) > CAST(UNIX_SECONDS(CURRENT_TIMESTAMP()) / (REFRESH_RATE_SEC) AS INT64) * (REFRESH_RATE_SEC) - (36 * 60 * 60)
> AND UNIX_SECONDS(log_time) < CAST(UNIX_SECONDS(CURRENT_TIMESTAMP()) / (REFRESH_RATE_SEC) AS INT64) * (REFRESH_RATE_SEC) - (36 * 60 * 60) + (REFRESH_RATE_SEC)
> ```

Comment where REFRESH_RATE_SEC comes from?

---

*[config/federation/bigquery/bq_ndt_tests2.sql, line 1 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH3boJaIZUHk_EGTai:-KyH3boJaIZUHk_EGTaj:b-anuyi1) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/config/federation/bigquery/bq_ndt_tests2.sql#L1)):*
> ```SQLPL
> -- TODO: Do not use Legacy SQL. Retire this script in favor of bq_ndt_test.sql.
> ```

Is this file still needed?  Will bqe just work with #standardSQL pragma?

---

*[config/federation/bigquery/ndt_test_count_total.sql, line 1 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH4ACFCw5nSTaBG8K2:-KyH4ACFCw5nSTaBG8K3:bhgxwg6) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/config/federation/bigquery/ndt_test_count_total.sql#L1)):*
> ```SQLPL
> SELECT                                                                          
> ```

Lots of spaces??  I'm seeing little red dots to the right.

---

*[config/federation/bigquery/ndt_test_count_total.sql, line 2 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH4dUXOSZAvHtANdxe:-KyH4dUXOSZAvHtANdxf:b-686d31) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/config/federation/bigquery/ndt_test_count_total.sql#L2)):*
> ```SQLPL
> SELECT                                                                          
>     828544145 + count(test_id) as value                                         
> ```

Would it be better to do this constant+ in Grafana?

---

*[k8s/prometheus-federation/deployments/bigquery-exporter.yml, line 1 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH5nlioIzjRChkrH9f:-KyH5nlioIzjRChkrH9g:b-ohbd3c) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/k8s/prometheus-federation/deployments/bigquery-exporter.yml#L1)):*
> ```YAML
> apiVersion: extensions/v1beta1
> ```

This is a lot of prometheus magic.  Could you add a short comment and link to relevant prometheus documentation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/120)*

**Comment by stephen-soltesz** [comment]
Thank you for the review, PTAL?

---

Review status: 3 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[apply-global-prometheus.sh, line 108 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH36XUuE0Cs_bMs23r:-KyHDKV3NpEmWXy0ryGU:b-3k4nbn) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/apply-global-prometheus.sh#L108)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Just curious - why the dry-run and pipe?  Can't do this directly?
</blockquote></details>

Correct, can't do this directly.

The `create --dry-run` generates a json configuration. `apply` sends it to the k8s API in a way that is repeatable. It is not possible to create an object that already exists, but one can be applied any number of times.

---

*[config/federation/bigquery/bq_ndt_tests.sql, line 1 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH3PWMGR4KpYoxTi1m:-KyHYGQ2zr9y5T0lkNNk:bnk1hph) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/config/federation/bigquery/bq_ndt_tests.sql#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Consider adding #standardSQL.  This both makes it obvious when reading, and serves as pragma to the query processor.

Add a short header comment?

Also, bq_ndt_test_counts.sql ?
</blockquote></details>

Added #standardSQL

Added short header comment.

I'm open to alternate file names. Using the `_counts` suffix is not recommended. It's ambiguous with the "counter" type (this is a gauge) and the unit (for lack of a better work) here is actually "tests".

---

*[config/federation/bigquery/bq_ndt_tests.sql, line 3 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH1yAFF0m3xIQSwv47:-KyHDmLW7I5wYfe1my-R:b-d6vn66) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/config/federation/bigquery/bq_ndt_tests.sql#L3)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

It is also easy to pull this out of the test_id with a regular expression.  Maybe preferable, since you are already using regexp below.
</blockquote></details>

I imagine regexp being much less efficient, right?

---

*[config/federation/bigquery/bq_ndt_tests.sql, line 24 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH2ma44m7TZvDDJN0f:-KyHYewQnOW-5A7tDWuB:b-896fix) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/config/federation/bigquery/bq_ndt_tests.sql#L24)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Comment where REFRESH_RATE_SEC comes from?
</blockquote></details>

Done.

---

*[config/federation/bigquery/bq_ndt_tests2.sql, line 1 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH3boJaIZUHk_EGTai:-KyHDx3E_Fy5FaOkQOrt:b-p2f7kn) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/config/federation/bigquery/bq_ndt_tests2.sql#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is this file still needed?  Will bqe just work with #standardSQL pragma?
</blockquote></details>

This is the "get things working" pr, using the v0.1 legacy sql syntax.

I'm also putting the pieces in place so that we can quickly switch bqe to supporting only standard sql. All that will take is: change bqe to use standard only, tag that version, and update these k8s configs, deleting the legacy files.

---

*[config/federation/bigquery/ndt_test_count_total.sql, line 1 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH4ACFCw5nSTaBG8K2:-KyHZ5ts1gBADK3dbA6Q:b-vbfwcx) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/config/federation/bigquery/ndt_test_count_total.sql#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Lots of spaces??  I'm seeing little red dots to the right.
</blockquote></details>

Weird paste error. Fixed.

---

*[config/federation/bigquery/ndt_test_count_total.sql, line 2 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH4dUXOSZAvHtANdxe:-KyHZ8MIP6kG6Ne39ga3:bnp8f3h) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/config/federation/bigquery/ndt_test_count_total.sql#L2)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Would it be better to do this constant+ in Grafana?
</blockquote></details>

That is an option. The alert pboothe defined last week expects the metric to be inclusive of all tests. I believe that using the constant here is simplest.

---

*[k8s/prometheus-federation/deployments/bigquery-exporter.yml, line 1 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH5nlioIzjRChkrH9f:-KyHZ_iddCzu_Qxohybl:b-v66lfr) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/k8s/prometheus-federation/deployments/bigquery-exporter.yml#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This is a lot of prometheus magic.  Could you add a short comment and link to relevant prometheus documentation?
</blockquote></details>

If we need better documentation for standard k8s configuraiton, I would like us to discuss creating that independently of these yaml configs.

This config is very boilerplate. Adding a comment here would probably be applied inconsistently and not universally helpful.

Would an update to the repo README be helpful? Something that contained an overview of the standard k8s types used by prometheus-support?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-:-KyHdMkCNFtwNk9oOIfJ:benzd2a)*

**Comment by gfr10598** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[config/federation/bigquery/bq_ndt_tests.sql, line 3 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH1yAFF0m3xIQSwv47:-KyI38BLbVi-MIh1_Ojb:b-xffzyw) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/config/federation/bigquery/bq_ndt_tests.sql#L3)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I imagine regexp being much less efficient, right?
</blockquote></details>

I doubt that it matters, but happy to leave it for another time/discussion.

---

*[k8s/prometheus-federation/deployments/bigquery-exporter.yml, line 1 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH5nlioIzjRChkrH9f:-KyI3eKIxszdEAxmx-tK:b9vdggm) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/k8s/prometheus-federation/deployments/bigquery-exporter.yml#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If we need better documentation for standard k8s configuraiton, I would like us to discuss creating that independently of these yaml configs.

This config is very boilerplate. Adding a comment here would probably be applied inconsistently and not universally helpful.

Would an update to the repo README be helpful? Something that contained an overview of the standard k8s types used by prometheus-support?
</blockquote></details>

Was mostly looking for a link or reference.  README might be good.  Ok to leave it for later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/120)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-:-KyI3tNW_VBstuxiaA_r:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Thank you!

---

Review status: 3 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[k8s/prometheus-federation/deployments/bigquery-exporter.yml, line 1 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-KyH5nlioIzjRChkrH9f:-KyI4zqXNicPEmeBlwOV:bkyf8g3) ([raw file](https://github.com/m-lab/prometheus-support/blob/969bfb059613e88d7fb8b03e2461cdc1ceb1f155/k8s/prometheus-federation/deployments/bigquery-exporter.yml#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Was mostly looking for a link or reference.  README might be good.  Ok to leave it for later.
</blockquote></details>

Okay, I've created an issue to add documentation or references for the most common k8s objects used by prometheus-support. https://github.com/m-lab/prometheus-support/issues/121

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-:-KyI5L12jAtlLec995vM:b-9755fn)*

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/120#-:-KyI9F3k5sbAHYnM5snp:bnfp4nl)*

**Pull request merged**
