### PR TITLE
Add autonode script exporter config

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds script exporter support for the autonode deployments.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1064)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
@nkinkade this PR is still draft but what do you think of it?

The primary motivation is to have some activity on the sandbox and staging autonode deployments for our internal monitoring and quality validation before we release a new version for others to use.

The main shortcoming currently is that this is testing VM to VM in GCE and the rates are probably much faster than they need to be for testing.

**Review by nkinkade — COMMENTED** [review]
It seems you've set the cache_exit_code.sh to cache for an hour, which seems reasonable. And according to [GCP VPC network pricing](https://cloud.google.com/vpc/network-pricing), intra-zone VPC networking is free, and inter-zone is $0.01/GiB. I see that currently the prometheus-federation cluster is deployed to us-central1-c, while the test autonode's are in us-central-a. Would it be possible to redeploy the test autonodes to us-central1-c? In that arrangement, it seems like the testing wouldn't incur any cost... as long as the traffic was using the VPC internal/private network addresses.

> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1064#-:-O9ksKPS8kfdLmABqoMc:bvnyl4h)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`k8s/prometheus-federation/deployments/script-exporter.yml` line 35 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/1064#-O9kvbc-4vnrvtVd0yy7:-O9kvbc-4vnrvtVd0yy8:b-qmsrcy) ([raw file](https://github.com/m-lab/prometheus-support/blob/12c806cb9bb764cfd9541ca9a57b75ab7eba5ce9/k8s/prometheus-federation/deployments/script-exporter.yml#L35)):*
> ```YAML
>       containers:
>       - name: script-exporter
>         image: measurementlab/script-exporter-support:sandbox-soltesz-add-ndt7
> ```

This seems like something that was meant for testing that didn't get changed back to the appropriate value?

**Review by nkinkade — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1064)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — COMMENTED** [review]
Thank you for taking such a careful look!

I've moved the autonode zone to us-central1-c in terraform - https://github.com/m-lab/terraform-support/pull/106 this requires a manual step to delete the node before deploying terraform since the provider is not strict about the zone and will keep a node in us-central1-a if it already exists there.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1064#-:-O9oyDUy4OqVs3gOa_R9:b-q9kie0)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[`k8s/prometheus-federation/deployments/script-exporter.yml` line 35 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/1064#-O9kvbc-4vnrvtVd0yy7:-O9oyoY42oNDl8jg8m0t:bmy6m75) ([raw file](https://github.com/m-lab/prometheus-support/blob/12c806cb9bb764cfd9541ca9a57b75ab7eba5ce9/k8s/prometheus-federation/deployments/script-exporter.yml#L35)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

This seems like something that was meant for testing that didn't get changed back to the appropriate value?
</blockquote></details>

Yes, it was only meant to be temporary while testing. Fixed now.

**Pull request merged**
