### PR TITLE
Removes script_success metrics from alerts + updates dashboards

### PR DESCRIPTION
**Pull request by nkinkade**
We are going to retire script_exporter, and along with e2e testing of ndt5. This commit removes the script_success metrics from any alerts in this repository. It also deletes one dashboard related to script_exporter, updates a Locate dashboard to not use the script_success metric.

While I was at it, I deleted a defunct "MLABNS_6_HourClients"  dashboard that seems to display no data and is probably no longer useful.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1052)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
I think we still want the script exporter for wehe - it has helped discover a number of issues - did we say we'd retire it entirely or only for ndt5? If anything, the script exporter is very helpful for early-stage service development (like it was for early stage ndt server deployments) when bugs are more frequent.

:lgtm: - as long as we're on the same page about the fate of the script exporter ultimately

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1052#-:-O4r7rix9qsPGN2Nvyve:brykv97)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[`config/federation/grafana/dashboards/MLABNS_6_HourClients.json` line 0 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/1052#-O4r8Ht25HJBofksVyk7:-O4r8Ht3A6v-pi_u9cld:bnrg27z) ([raw file](https://github.com/m-lab/prometheus-support/blob/26b2669df80c53abc488f63840075f39e44359fa/config/federation/grafana/dashboards/MLABNS_6_HourClients.json#L0)):*
This is good to remove
___
*[`config/federation/prometheus/alerts.yml` line 126 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/1052#-O4r8mgIBJU3d35QAFcR:-O4r8mgIBJU3d35QAFcS:b-1si7yd) ([raw file](https://github.com/m-lab/prometheus-support/blob/b5b9aaa70dc84f71315522b8d13f147984b53647/config/federation/prometheus/alerts.yml#L126)):*
> ```YAML
> # be present. The wait period should be longer than that for the
> # ScriptExporterDownOrMissing alert.
>   - alert: ScriptExporterMissingMetrics
> ```

If other alerts don't already exist to check that the script exporter is up, can this alert be made generic for other services other than ndt5?

**Review by nkinkade — COMMENTED** [review]
From our conversations around script_exporter over the past few weeks, my impression had been that we were all in agreement to just retire it outright, for ndt5 and wehe. We may have only talked about ndt5 in specific, but I had, perhaps incorrectly, inferred that we were effectively talking about the whole thing.

Are we using the script_success metrics for wehe anywhere? I couldn't find any alert or dashboard where this was true, and I know that I certainly haven't ever looked at how often the e2e test of wehe is or isn't failing. Are you saying that we should keep it for wehe because it is currently useful for wehe, or that it was in the past useful for wehe and that it may be useful for some future experiment that doesn't yet exist?

Indeed, it was an oversight that I didn't also remote the alert `ScriptExporterDownOrMissing`, on which you left a comment.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1052#-:-O4v2jsR4_jeIPyfZZM7:b-77h44m)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
It's understandable that script exporter has become synonymous with ndt5 - especially if the ndt5 metric is the only one we use in practice. If I contributed to that conflation or wasn't clear in those conversations, I'm sorry - lately, I am noticing how often I don't seem to communicate clearly.

The situations for wehe I'm thinking of is simply in sandbox when we trial a new build - the script exporter automatically runs a fixed set of tests - that alone has been enough to uncover many issues with the new build - my sense is that this automation is simpler to rely on than manually running tests - or relying on the wehe team to run adhoc tests

I think you're right that we don't have alerts for the script exporter for any other experiment.

I do imagine the script exporter being helpful for future experiments in their early stage just as it was for early ndt and current wehe.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1052#-:-O4v7DbM-VTpAUec5Swi:bf74emg)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @nkinkade)

**Review by nkinkade — COMMENTED** [review]
How about we pin script_exporter to sandbox, test only wehe, and reduce the frequency of runs from every 1 to 15 minutes, to maybe hourly?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1052#-:-O4vIjuE2GB0QfDeEIZh:b8fjdrv)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
No objections

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1052#-:-O4vMYTQ6-IDNk1K_pya:bxkyl7o)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @nkinkade)

**Review by nkinkade — COMMENTED** [review]
I added back the `ScriptExporterMissingMetrics`, but now with label `service="wehe_client"` instead of ndt5. 

One final look?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1052#-:-O4vXSQDEhHaqjd7KFaJ:bstsa6j)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: - just clarifying, this would keep the script exporter in all projects then?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1052#-:-O4v_6VZ-kWWwPZE3awD:b-y2imk7)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @nkinkade)

**Review by nkinkade — COMMENTED** [review]
Good point. I don't know of a way to pin alerts to a particular project. Maybe this means we need to keep it running everywhere, unless I'm missing something?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1052#-:-O4vb2wZAx9aSRT7p8-V:b4v1xee)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: per our conversation this morning in the Ops Tactical meeting, I have updated this PR to remove the two alerts related to script_exporter. We will pin script exporter to sandbox, and so decided we don't need the alerts for this service in that situation.  Could you give one final look at this PR?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1052#-:-O5FhLGn3EAupoQ2mYtB:bg1zbyz)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1052#-:-O5Flmc_9ZdBI015ya6C:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @nkinkade)

**Pull request merged**
