### PR TITLE
Adds link to alert description on how to resize Prom VM's disk.

### PR DESCRIPTION
**Pull request by nkinkade**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/762)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: with one change.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/762#-:-MLj2R_fCr8r0QmWxwap:b-5w8w13)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[config/federation/prometheus/alerts.yml, line 963 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/762#-MLj2DJ58Vkboj2-uzx0:-MLj2DJ58Vkboj2-uzx1:b-m55s1s) ([raw file](https://github.com/m-lab/prometheus-support/blob/d1c106428028a04ef8a6f6a82509cc8bd91f5720/config/federation/prometheus/alerts.yml#L963)):*
> ```YAML
>         fires it means that the size of the persistent disk is too small and
>         may need to be increased. GCE persistent disks can be resized, even on
>         a running VM. [Instructions on how to do this](https://github.com/m-lab/k8s-support/blob/master/manage-cluster/PROMETHEUS.md#resizing-the-prometheus-vms-disk) are in the k8s-support repo.
> ```

Please prefer the citation style markdown for easier formatting and legibility of the raw text.

i.e.
```
 [Instructions on how to do this][1] are in the k8s-support repo.

[1]: https://github.com/m-lab/k8s-support/blob/master/manage-cluster/PROMETHEUS.md#resizing-the-prometheus-vms-disk
```

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/762)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/federation/prometheus/alerts.yml, line 963 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/762#-MLj2DJ58Vkboj2-uzx0:-MLj68b01QnLrIbaQDpI:b-896fix) ([raw file](https://github.com/m-lab/prometheus-support/blob/d1c106428028a04ef8a6f6a82509cc8bd91f5720/config/federation/prometheus/alerts.yml#L963)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please prefer the citation style markdown for easier formatting and legibility of the raw text.

i.e.
```
 [Instructions on how to do this][1] are in the k8s-support repo.

[1]: https://github.com/m-lab/k8s-support/blob/master/manage-cluster/PROMETHEUS.md#resizing-the-prometheus-vms-disk
```
</blockquote></details>

Done.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/762)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[config/federation/prometheus/alerts.yml, line 963 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/762#-MLj2DJ58Vkboj2-uzx0:-MLj9ydY-CLSbiQLIbIY:bu1vwt2) ([raw file](https://github.com/m-lab/prometheus-support/blob/d1c106428028a04ef8a6f6a82509cc8bd91f5720/config/federation/prometheus/alerts.yml#L963)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please see my example. Your change is incorrect md format.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/762)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[config/federation/prometheus/alerts.yml, line 963 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/762#-MLj2DJ58Vkboj2-uzx0:-MLjA6_U8_vzuIhU4UUP:bwlgvxk) ([raw file](https://github.com/m-lab/prometheus-support/blob/d1c106428028a04ef8a6f6a82509cc8bd91f5720/config/federation/prometheus/alerts.yml#L963)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please see my example. Your change is incorrect md format.
</blockquote></details>

Also see any of the other examples in this file. :)

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/762)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/federation/prometheus/alerts.yml, line 963 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/762#-MLj2DJ58Vkboj2-uzx0:-MLjB-JXDHG8-2yAuXcy:b-xpr1je) ([raw file](https://github.com/m-lab/prometheus-support/blob/d1c106428028a04ef8a6f6a82509cc8bd91f5720/config/federation/prometheus/alerts.yml#L963)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Also see any of the other examples in this file. :)
</blockquote></details>

Is your issue that I'm missing a colon after `[1]`?  I did take a look at some other examples in the file, and notwithstanding the missing colon it seem to follow the other similar uses. For example:

https://github.com/m-lab/prometheus-support/blob/master/config/federation/prometheus/alerts.yml#L103

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/762)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[config/federation/prometheus/alerts.yml, line 963 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/762#-MLj2DJ58Vkboj2-uzx0:-MLjBbPx1F9RlyPMak6m:b-1ycjk7) ([raw file](https://github.com/m-lab/prometheus-support/blob/d1c106428028a04ef8a6f6a82509cc8bd91f5720/config/federation/prometheus/alerts.yml#L963)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is your issue that I'm missing a colon after `[1]`?  I did take a look at some other examples in the file, and notwithstanding the missing colon it seem to follow the other similar uses. For example:

https://github.com/m-lab/prometheus-support/blob/master/config/federation/prometheus/alerts.yml#L103
</blockquote></details>

Eeek! Do those work? Those look wrong to me. My understanding is that links need to include:

```
[link text][ref]

[ref]: http://some.link/resource
```

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/762)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/federation/prometheus/alerts.yml, line 963 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/762#-MLj2DJ58Vkboj2-uzx0:-MLjFHJG62obMe393A5-:b5spd1d) ([raw file](https://github.com/m-lab/prometheus-support/blob/d1c106428028a04ef8a6f6a82509cc8bd91f5720/config/federation/prometheus/alerts.yml#L963)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Eeek! Do those work? Those look wrong to me. My understanding is that links need to include:

```
[link text][ref]

[ref]: http://some.link/resource
```
</blockquote></details>

I fixed my incorrect usage, and also fixed all the other incorrect usages in the file. PTAL?

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: - Thank you!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/762#-:-MLjPSCgCAHCkQarmJai:bsjzsje)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
