### PR TITLE
Add Rollout panels

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR adds a "Rollout" row for the Locate Service dashboard.

https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service?orgId=1&refresh=5m&from=now-4d&to=now&var-datasource=Prometheus%20%28mlab-sandbox%29&var-platformdatasource=Platform%20Cluster%20%28mlab-sandbox%29&var-bigquerydatasource=BigQuery%20%28mlab-sandbox%29&var-experiment=ndt

The panels added have comparisons between the Locate Service and Mlab-ns for the following metrics:

- Healthy server counts.
- Distribution of distances from client to server.
- Min, median, and max number of tests across sites within metros.
- Number of tests per machine in a site.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/963)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/963)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cloudbuild.yaml` line 126 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/963#-NIry_jMA2I6oMgqnF9D:-NIry_jMA2I6oMgqnF9E:b-sxjji8) ([raw file](https://github.com/m-lab/prometheus-support/blob/ce7c5f102a9575777be50b14a5c43951eb1f47d6/cloudbuild.yaml#L126)):*
> ```YAML
>     # Install new GKE kubectl auth plugin
>     # https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
>     apt update && apt install -y google-cloud-sdk-gke-gcloud-auth-plugin
> ```

This was causing the [build](https://pantheon.corp.google.com/cloud-build/builds;region=global/8c34189e-e121-45e0-bcbc-1d53aa844459?project=mlab-sandbox) to fail.

**Review by stephen-soltesz — COMMENTED** [review]
The panels that enumerate sites and nodes-within sites currently all fit b/c there are only a few sites in sandbox. Will the presentation work for the number of sites in production? (I tried selecting other projects but it didn't display anything yet, which may be expected).

The "Healthy Server Count" panel looks close when "ndt" is selected. The difference is unexplainable by me when I change the experiment to "msak". What is happening here?

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/963#-:-NIsHnVwDHwj-s6zGkcV:b-pca1pi)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cloudbuild.yaml` line 126 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/963#-NIry_jMA2I6oMgqnF9D:-NIsG-ee3wXsacqdrpBB:b-2q0dad) ([raw file](https://github.com/m-lab/prometheus-support/blob/ce7c5f102a9575777be50b14a5c43951eb1f47d6/cloudbuild.yaml#L126)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

This was causing the [build](https://pantheon.corp.google.com/cloud-build/builds;region=global/8c34189e-e121-45e0-bcbc-1d53aa844459?project=mlab-sandbox) to fail.
</blockquote></details>

Thank you for the fix.
___
*[`config/federation/grafana/dashboards/Locate_Service.json` line 241 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/963#-NIsG5_f0bl3bRBUp7S0:-NIsG5_f0bl3bRBUp7S1:b-z5tbil) ([raw file](https://github.com/m-lab/prometheus-support/blob/f50beab1bae05277d113e84b285aa9a448f68389/config/federation/grafana/dashboards/Locate_Service.json#L241)):*
> ```JSON
>           ],
>           "timeColumn": "-- time --",
>           "timeColumnType": "TIMESTAMP",
> ```

In the panel configurations using the BQ data source, the queries require a pattern that references the `date` as well as using the `$__timeFilter` macro.

The panel JSON includes the settings:
```
      "timeColumn": "-- time --",
      "timeColumnType": "TIMESTAMP",
```


In panels like these https://grafana.mlab-sandbox.measurementlab.net/d/k1guUtsnz/bigquery-ndt7-downloads-clients-zones-etc?orgId=1&editPanel=5 the query can use `date` directly in the `$__timeFilter` macro. To use this, (I believe) the panel JSON must include these settings.

```
      "partitioned": true,
      "partitionedField": "date",
      "timeColumn": "date",
      "timeColumnType": "DATE",
```

Unfortunately, I have not found a direct way to manipulate this setting via the UI. But, it simplifies the BQ query syntax, and allows us to run the query over any time period efficiently.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/963#-:-NJ5S8q17yU6kR-jWNRb:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

**Comment by cristinaleonr** [comment]
Part of https://github.com/m-lab/locate/issues/102.

**Pull request merged**
