### PR TITLE
Update Grafana and enable Google OAuth login

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds support for Grafana login using Google OAuth.

The client secret and client id are stored as secure environment variables in the travis environment and available and deploy time.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/95)

### CODE REVIEW

**Comment by nkinkade** [comment]
One clarifying question, which is probably just me not understanding something.

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[apply-global-prometheus.sh, line 73 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/95#-Kw_qPoisb1ezAL8Fu3Y:-Kw_qPoisb1ezAL8Fu3Z:b-71f28o) ([raw file](https://github.com/m-lab/prometheus-support/blob/ed7b42486cccfa342ed858e95a91a1125d41a051/apply-global-prometheus.sh#L73)):*
> ```Shell
> kubectl create configmap grafana-env \
>     "--from-literal=domain=${GRAFANA_DOMAIN}" \
>     "--from-literal=gf_auth_google_client_secret=${!GF_CLIENT_SECRET_NAME}" \
> ```

For some reason I'm not seeing the purpose of the indirection here. Why not just?:

`"--from-literal=gf_auth_google_client_secret=GF_AUTH_GOOGLE_CLIENT_SECRET_${PROJECT/-/_}"`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/95#-:-Kw_r5WvEC7YdLwrqhtq:b-9267e2)*

**Comment by stephen-soltesz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[apply-global-prometheus.sh, line 73 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/95#-Kw_qPoisb1ezAL8Fu3Y:-Kw_sToF1IHkDCj-391x:b-vndvkq) ([raw file](https://github.com/m-lab/prometheus-support/blob/ed7b42486cccfa342ed858e95a91a1125d41a051/apply-global-prometheus.sh#L73)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

For some reason I'm not seeing the purpose of the indirection here. Why not just?:

`"--from-literal=gf_auth_google_client_secret=GF_AUTH_GOOGLE_CLIENT_SECRET_${PROJECT/-/_}"`
</blockquote></details>

So, this is the first time that I've used pre-stored environment variables in travis to distribute secrets. So, there will be pre-defined environment variables for sandbox, staging, and mlab-oti. These expressions are to extract the right value for each project.

With the expression in your question, the configmap would contain:

key: gf_auth_google_client_secret
value: GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_sandbox

But, we need the configmap value to equal the value stored *in* the named variable. That is the actual secret. Does that help?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/95)*

**Comment by nkinkade** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[apply-global-prometheus.sh, line 73 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/95#-Kw_qPoisb1ezAL8Fu3Y:-Kw_uFUVeF3UOY9ksN2S:b-9bocbb) ([raw file](https://github.com/m-lab/prometheus-support/blob/ed7b42486cccfa342ed858e95a91a1125d41a051/apply-global-prometheus.sh#L73)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

So, this is the first time that I've used pre-stored environment variables in travis to distribute secrets. So, there will be pre-defined environment variables for sandbox, staging, and mlab-oti. These expressions are to extract the right value for each project.

With the expression in your question, the configmap would contain:

key: gf_auth_google_client_secret
value: GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_sandbox

But, we need the configmap value to equal the value stored *in* the named variable. That is the actual secret. Does that help?
</blockquote></details>

Sorry, what I meant was this:

`"--from-literal=gf_auth_google_client_secret=${GF_AUTH_GOOGLE_CLIENT_SECRET_}${PROJECT/-/_}"

Unless it's used somewhere else, why not just drop the intermediary name? Sorry if I'm just not understanding.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/95)*

**Comment by stephen-soltesz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[apply-global-prometheus.sh, line 73 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/95#-Kw_qPoisb1ezAL8Fu3Y:-Kwa-mNf2tcY_wXRXLO5:bjpb4ql) ([raw file](https://github.com/m-lab/prometheus-support/blob/ed7b42486cccfa342ed858e95a91a1125d41a051/apply-global-prometheus.sh#L73)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Sorry, what I meant was this:

`"--from-literal=gf_auth_google_client_secret=${GF_AUTH_GOOGLE_CLIENT_SECRET_}${PROJECT/-/_}"

Unless it's used somewhere else, why not just drop the intermediary name? Sorry if I'm just not understanding.


</blockquote></details>

This is the environment we're starting with, created by the deploy scripts and travis.
```
PROJECT=mlab-sandbox
GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_sandbox=somesecret
GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_staging=somesecret2
GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_oti=somesecret3
```

Based on the project value, we need to lookup the secret corresponding to that project.

If we knew that we needed the sandbox value, we could just reference that directly like usual:
```
$GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_sandbox
```

In our case, we would like a script to handle multiple cases. Bash also supports indirect variable dereferencing. The `${!<name>}` syntax makes:
```
VARNAME=GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_sandbox
${!VARNAME}
```

Work the same way this works:
```
$GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_sandbox
```

So, the intermediate name is necessary to construct the variable name we want.

Does this answer your question?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/95)*

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[apply-global-prometheus.sh, line 73 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/95#-Kw_qPoisb1ezAL8Fu3Y:-Kwa4X1SuDNsFxe8sVES:bily6mc) ([raw file](https://github.com/m-lab/prometheus-support/blob/ed7b42486cccfa342ed858e95a91a1125d41a051/apply-global-prometheus.sh#L73)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This is the environment we're starting with, created by the deploy scripts and travis.
```
PROJECT=mlab-sandbox
GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_sandbox=somesecret
GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_staging=somesecret2
GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_oti=somesecret3
```

Based on the project value, we need to lookup the secret corresponding to that project.

If we knew that we needed the sandbox value, we could just reference that directly like usual:
```
$GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_sandbox
```

In our case, we would like a script to handle multiple cases. Bash also supports indirect variable dereferencing. The `${!<name>}` syntax makes:
```
VARNAME=GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_sandbox
${!VARNAME}
```

Work the same way this works:
```
$GF_AUTH_GOOGLE_CLIENT_SECRET_mlab_sandbox
```

So, the intermediate name is necessary to construct the variable name we want.

Does this answer your question?
</blockquote></details>

Yes. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/95#-:-Kwa4_zETgWAhAOf3Yye:bnfp4nl)*

**Pull request merged**
