### PR TITLE
Support generating k8s configuration from templates

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change is the first of a sequence of changes that should consolidate the k8s configs under the `k8s/<project>` directories.

In particular, these configs only differ by a few values that can now be specified using a per-project template file.

This change starts with the mlab-sandbox scraper-cluster.

* `k8s/mlab-sandbox/scraper-cluster` is moved to `k8s/scraper-cluster`.  This location will be the basis of the eployment in all projects.
* `k8s/scraper-cluster/mlab-sandbox.yml` is the per-project settings file, currently only supporting sandbox.

The template support is provided by https://github.com/kopeio/kexpand

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/98)

### CODE REVIEW

**Comment by nkinkade** [comment]
One very small clarifying question for my own edification.

---

Reviewed 15 of 16 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[apply-cluster.sh, line 29 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/98#-KwfynnjeI6fPGTgQ2Fm:-KwfynnjeI6fPGTgQ2Fn:bdtjvnd) ([raw file](https://github.com/m-lab/prometheus-support/blob/5b3e67aab357c40dc160970a273b98226c615da6/apply-cluster.sh#L29)):*
> ```Shell
>     CFG=/tmp/${CLUSTER}-${PROJECT}.yml && rm -f ${CFG}
>     kexpand expand k8s/${CLUSTER}/*/*.yml \
>         -f k8s/${CLUSTER}/${PROJECT}.yml >> ${CFG}
> ```

Out of curiosity, why is this an append operation? Could we make this an overwrite operation and skip the `rm -f ${CFG}` above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/98#-:-KwfzcJe1cPiAC03wP9D:b1mrhwo)*

**Comment by stephen-soltesz** [comment]
PTAL?

---

Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[apply-cluster.sh, line 29 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/98#-KwfynnjeI6fPGTgQ2Fm:-Kwg-Bm5bZ6lBfQ4y2ON:b-66ryps) ([raw file](https://github.com/m-lab/prometheus-support/blob/5b3e67aab357c40dc160970a273b98226c615da6/apply-cluster.sh#L29)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Out of curiosity, why is this an append operation? Could we make this an overwrite operation and skip the `rm -f ${CFG}` above?
</blockquote></details>

Good question. I was experimenting with different template tools before settling on this one. In previous iterations I needed to explicltly iterate over each file and appended them, but you're right to point out that kexpand is operating on all files at once and writing the output once is simpler. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/98#-:-Kwg-Q66MVIzRaFY4cOu:b-833305)*

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/98#-:-Kwg0TRprygdK11CpC7-:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Thank you!

**Pull request merged**
