### PR TITLE
Add separate 3h instance for expensive queries

### PR DESCRIPTION
**Pull request by gfr10598**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/755)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/755)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

___
*[k8s/prometheus-federation/deployments/bigquery-exporter-3h.yml, line 4 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/755#-MKH_OP2BTg_xVqhnvNs:-MKH_OP319w-JSI0el_O:b-70suac) ([raw file](https://github.com/m-lab/prometheus-support/blob/413ba718a98b9e58a176f9056a45affb0b1c49aa/k8s/prometheus-federation/deployments/bigquery-exporter-3h.yml#L4)):*
> ```YAML
> kind: Deployment
> metadata:
>   name: bigquery-exporter
> ```

I think the name and run labels should be updated. Otherwise, only one of these configs will be applied.

The deployment from travis succeeded, but if you look at the deployments / pods in sandbox cluster, what do you see?

It should be okay for multiple deployments to mount the same configmap. And, each deployment pod should get it's own IP so, the port is okay.

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/755)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[k8s/prometheus-federation/deployments/bigquery-exporter-3h.yml, line 4 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/755#-MKH_OP2BTg_xVqhnvNs:-MKKeuCH51iwUGnrRyHk:bb6un1j) ([raw file](https://github.com/m-lab/prometheus-support/blob/413ba718a98b9e58a176f9056a45affb0b1c49aa/k8s/prometheus-federation/deployments/bigquery-exporter-3h.yml#L4)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I think the name and run labels should be updated. Otherwise, only one of these configs will be applied.

The deployment from travis succeeded, but if you look at the deployments / pods in sandbox cluster, what do you see?

It should be okay for multiple deployments to mount the same configmap. And, each deployment pod should get it's own IP so, the port is okay.
</blockquote></details>

Done

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/755)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[k8s/prometheus-federation/deployments/bigquery-exporter-3h.yml, line 4 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/755#-MKH_OP2BTg_xVqhnvNs:-MKKr3l21hfkIDFc-ERs:balu13s) ([raw file](https://github.com/m-lab/prometheus-support/blob/413ba718a98b9e58a176f9056a45affb0b1c49aa/k8s/prometheus-federation/deployments/bigquery-exporter-3h.yml#L4)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Did not work with labels changed.  With just unique names, seems to be WAI.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: -- make sure the old name is deleted manually in each project before deploying this (or we'll have three instances) -- alternately only rename the new deployment with `*-3h`.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/755#-:-MKKrMkY4eNPfp1DKIZK:b-6byhz2)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

**Pull request merged**
