### PR TITLE
Add initial dashboard for Locate service

### PR DESCRIPTION
**Pull request by cristinaleonr**
https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service?orgId=1&var-datasource=Prometheus%20(mlab-sandbox)

This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/930)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Number of Requests - please specify number of client requests (to differentiate from heartbeats). Same with failure rates.

Request Failure Rate (Hourly) - please include the status label value in the aggregation, e.g. `sum by(status) ..` so the legend includes this information. This could help direct users of the dashboard toward a root cause faster.

Is it possible to calculate a heartbeat reconnection rate? Seeing a timeseries of that could be instructive about major events/disruptions on the platform.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/930#-:-N84ocfM2AYQzrl0bDMQ:b2425uy)* status: 0 of 1 approvals obtained

**Review by cristinaleonr — COMMENTED** [review]
Thank you. PTAL? https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/930#-:-N85Q4_K986hqsa5CwR2:bmkc4g3)* status: 0 of 1 approvals obtained

**Review by cristinaleonr — COMMENTED** [review]
Updated the datasource https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service?orgId=1

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/930#-:-N85Tdld3KVe3iI6l_Ya:b-ktvknh)* status: 0 of 1 approvals obtained

**Review by stephen-soltesz — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/930)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
