### PR TITLE
Add Prometheus and health panels to Locate dashboard

### PR DESCRIPTION
**Pull request by cristinaleonr**
https://grafana.mlab-sandbox.measurementlab.net/d/8O9tInk4k/locate-service

This PR adds 3 new panels to the dashboard. One for /health checks (Health Checks) and two for Prometheus health collections (Prometheus Health Collections and Prometheus Health Collection Request Time). 

It also moves the "Health" row to the top.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/959)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Provided feedback in person, including:
* label y axes with units, preferring /s or /min
* use whole space
* filter by service e.g. ndt/msak/other
* make it easy to relate the expected number of instances to the expected aggregate values for other metrics (health checks/ports, etc)

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/959#-:-NGr33ce2fhxlANTGAGe:bwpjl4j)* status: 0 of 1 approvals obtained

**Review by cristinaleonr — COMMENTED** [review]
* Added /min metrics to the corresponding y axes
* Widened the panels
* Separated the health signals row into Locate and HBS
* Added an experiment filter and linked it to the "Current Heartbeat Connections" panel and the panels in the "Health Signals from Heartbeat Service"
* Now it's easy to relate the expected number of instances to the aggregate values. For example, after selecting "ndt" in the experiment filter (msak instances are not exposing metrics), the "Current Heartbeat Connections" panel shows that there are 11 ndt instances connected and the "Health Checks (per min)" panel shows there are 66 health checks per minute (one check every ten seconds means **6** checks per instance per minute and 66/11 = **6**).

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/959#-:-NGxGu8t5LCPXa3zwGLS:bnv3taj)* status: 0 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
We talked about a few other potential refinements. Would you like to checkpoint this here?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/959#-:-NH0UF1x5s79YJ3REVsc:b-eyvrt5)* status: 0 of 1 approvals obtained

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/959#-:-NH0eyqP7276b9ElwMSO:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
