### PR TITLE
Update links referencing main branch

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change continues work to update github branches to use `main`. This change updates links in configuration to use the main branch where appropriate.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/942)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
@nkinkade ^ I see cloud builds for sandbox and staging above. I only expect to see sandbox. Let's review the setup.

**Review by SaiedKazemi — APPROVED** [review]
These changes look good to me but when I search for master I see a lot of other files in this repo:
```
$ git grep -lw master
IPV6_MONITORING.md
README.md
config/cluster/prometheus/prometheus.yml.template
config/federation/alertmanager/config.yml.template
config/federation/grafana/dashboards/K8s_EtcdOverview.json
config/federation/grafana/dashboards/K8s_MasterCluster.json
config/federation/grafana/grafana.ini
config/federation/prometheus/prometheus.yml.template
generate-prometheus-targets.sh
k8s/data-processing/deployments/prometheus.yml
k8s/prometheus-federation/deployments/alertmanager.yml
k8s/prometheus-federation/deployments/blackbox.yml
k8s/prometheus-federation/deployments/gcs-exporter.yml
k8s/prometheus-federation/deployments/grafana.yml
k8s/prometheus-federation/deployments/prometheus.yml
```
Should we also fix them in this PR or do it later?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/942#-:-NA59ft1DKTYU5Y1pG99:bn5cy1b)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
I've updated additional references to main branches in URLs in comments. Some of the hits above are different, i.e. "master cluster" or correct (no main branch exists upstream yet).

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/942#-:-NA5Cd3o0m28fYkOXgb3:b-xpf8sd)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by SaiedKazemi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/942#-:-NA5URd-BHZrO8VO26y0:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
