### PR TITLE
lower the alert bar for gardener slow processing

### PR DESCRIPTION
**Pull request by yachang**
https://github.com/m-lab/prometheus-support/issues/769

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/770)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Can you describe how you arrived at this solution? What is the metric `bq_gardener_daily_done_last_4_days` measuring? What would it mean if `bq_gardener_daily_done_last_4_days` were always == 2?

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/770#-:-MOlZhIp6YjYWMY-koQz:b-v52oxs)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by yachang — COMMENTED** [review]
The basic idea is to lower the bar for alert firing. If the bq_gardener_daily_done_last_4_days is always 2, which means that the moving window for daily processing done is 48 hours (4-2 =2 days), which matches what you described in the issue:

"The alert threshold should be updated to allow for this case over short periods of time, e.g. 24-48 hrs."

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/770#-:-MOlrng35RAObw99F8b0:bfmqlj9)* status: 0 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
The proposed change would allow `bq_gardener_daily_done_last_4_days == 2` indefinitely. But, we expect most days will have `bq_gardener_daily_done_last_4_days == 4` at some point. And, if too many days (over 48hrs) don't have "4 daily done in the last 4 days" then that's worth alerting someone about.

What about:

```
    expr: |
      bq_gardener_daily_done_last_4_days < 4
    for: 48h
```

This increases the window of time without reducing the expected quantity within that window.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/770#-:-MOmi6sg3-dHXwo5VMNW:bgxsa81)* status: 0 of 1 approvals obtained

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/770#-:-MOnULctCCJaAydzj_l3:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
