### PR TITLE
Prepare for data-pipeline us-central1 migration

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change updates the k8s configuration and documentation for the prometheus configuration used by the new data-pipeline cluster. This includes

* Updating the version of kube-state-metrics to support the latest K8s APIs (some deprecated since 1.24)
* Changing the initContainers to reference the root directory rather than a directory that does not exist for a new cluster
* Updates to many dashboards referencing data-pipeline rather than data-processing
* Adds three new data source definitions for the new cluster. The old data sources will remain for now, to be removed after migration to the new cluster is complete.
* Alert updates to reference the new cluster name

I do expect that some alerts will fire once deployed since the history of metrics in staging will not begin until these changes are deployed.

Part of:
* https://github.com/m-lab/etl/issues/1092

Before deployment, operator must manually add Cloud Build SA to the data-pipeline cluster rolebinding:

```
kubectl create clusterrolebinding additional-cluster-admins \
   --clusterrole=cluster-admin  --user=<projectnumber>@cloudbuild.gserviceaccount.com
```

After deployment, operator must manually adding a DNS record for the prometheus-data-pipeine.$PROJECT.measurementlab.net datasource using the allocated IP in the data-pipeline cluster.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1002)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
I have verified the following dashboards appear to work as intended in sandbox with the new data-pipeline cluster and changes in this PR:

*  [config/federation/grafana/dashboards/Pipeline_Overview.json](https://grafana.mlab-sandbox.measurementlab.net/d/UTgnK-jMz/pipeline-overview?orgId=1&var-project=mlab-sandbox&var-PrometheusDS=Prometheus%20%28mlab-sandbox%29&var-Gardener2_DS=Data%20Pipeline%20%28mlab-sandbox%29&var-states2=complete&var-datatype=annotation2&var-datatype=hopannotation2&from=now-24h&to=now)
*  [config/federation/grafana/dashboards/Pipeline_AlternativeSLIs.json](https://grafana.mlab-sandbox.measurementlab.net/d/q4MrNzh7k/pipeline-slis?orgId=1&var-project=mlab-sandbox&var-PrometheusDS=Prometheus%20%28mlab-sandbox%29&var-Gardener2_DS=Data%20Pipeline%20%28mlab-sandbox%29)
*  [config/federation/grafana/dashboards/Pipeline_Autoloader.json](https://grafana.mlab-sandbox.measurementlab.net/d/OKQmdgs4k/pipeline-autoloader?orgId=1&from=now-24h&to=now)
*  [config/federation/grafana/dashboards/Stats_Pipeline_Monitoring.json](https://grafana.mlab-sandbox.measurementlab.net/d/07rwXefMz/stats-pipeline-monitoring?orgId=1&var-datasource=Data%20Pipeline%20%28mlab-sandbox%29&from=now-2d&to=now)
*  [config/federation/grafana/dashboards/Prometheus_SelfMonitoring.json](https://grafana.mlab-sandbox.measurementlab.net/d/sVklmeHik/prometheus-self-monitoring?orgId=1&var-datasource=Data%20Pipeline%20%28mlab-sandbox%29)
*  [config/federation/grafana/dashboards/Pipeline_Gardener.json](https://grafana.mlab-sandbox.measurementlab.net/d/eBbUW6oik/pipeline-gardener?orgId=1&refresh=5m&var-project=mlab-sandbox&var-pipelineDatasource=Data%20Pipeline%20%28mlab-sandbox%29&var-prometheusDatasource=Prometheus%20%28mlab-sandbox%29&var-deployment=All&var-datatypes=All)
*  [config/federation/grafana/dashboards/Stats_Pipeline_AnnotationExportMonitoring.json](https://grafana.mlab-sandbox.measurementlab.net/d/XokjBPKnj/stats-pipeline-annotation-export-monitoring?orgId=1&refresh=1m&var-datasource=Data%20Pipeline%20%28mlab-sandbox%29)

I cannot test the following dashboards:

*  config/federation/grafana/dashboards/KeepMLabRunning.json -- pinned to oti
*  config/federation/grafana/dashboards/Archive_Repacker_Annotations.json -- not running

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1002#-:-NccfWqrEwYvq-BPR1E3:bcl0gh1)* status: 0 of 1 approvals obtained

**Review by nkinkade — CHANGES_REQUESTED** [review]
@stephen-soltesz: Everything seems mostly okay. I added a couple very minor comments, and one possible blocker on the Stats Pipeline Monitoring dashboard.

> Reviewed 28 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1002#-:-NchcP8053z6gt8Ch6XI:b-7x8srx)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`config/federation/grafana/dashboards/Pipeline_AlternativeSLIs.json` line 0 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/1002#-NchaLAN2gcllXleD8C0:-NchaLAN2gcllXleD8C1:b-75ca4v) ([raw file](https://github.com/m-lab/prometheus-support/blob/3029460a46714f8060487cae371cf86938be7e62/config/federation/grafana/dashboards/Pipeline_AlternativeSLIs.json#L0)):*
Just noting that it is a very mildly confusing that the file name of the dashboard is `Pipeline_AlternativeSLIs`, while the name of the dashboard in Grafana is `Pipeline SLIs` (minus "Alternative").
___
*[`config/federation/grafana/dashboards/Stats_Pipeline_Monitoring.json` line 1652 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/1002#-NchcAJd-PWwJvTJnmo-:-NchcAJd-PWwJvTJnmo0:bbn7a9z) ([raw file](https://github.com/m-lab/prometheus-support/blob/3029460a46714f8060487cae371cf86938be7e62/config/federation/grafana/dashboards/Stats_Pipeline_Monitoring.json#L1652)):*
> ```JSON
>   "time": {
>     "from": "2021-02-22T21:32:03.609Z",
>     "to": "2021-02-23T00:26:27.766Z"
> ```

Is `from`:`to` supposed to be set like this by default. When I load the dashboard it shows no data, and the date range is configured for a range from last year. I suspect this is unintentional.
___
*[`config/federation/grafana/provisioning/datasources/data-pipeline_mlab-sandbox.yml.template` line 16 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/1002#-NchT_56-T8kRyNrPd9I:-NchT_56-T8kRyNrPd9J:b-ouku0n) ([raw file](https://github.com/m-lab/prometheus-support/blob/3029460a46714f8060487cae371cf86938be7e62/config/federation/grafana/provisioning/datasources/data-pipeline_mlab-sandbox.yml.template#L16)):*
> ```
>   orgId: 1
>   # <string> url
>   url: http://prometheus-data-pipeline.mlab-sandbox.measurementlab.net:9090
> ```

Just noting that I see this new domain in Cloud DNS in sandbox, but not in staging and mlab-oti. I imagine it will need to be manually created in staging and mlab-oti.
___
*[`k8s/data-pipeline/mlab-oti.yml` line 0 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/1002#-NchZBcw5d8dFBnn53fI:-NchZBcw5d8dFBnn53fJ:b-fwgr76) ([raw file](https://github.com/m-lab/prometheus-support/blob/3029460a46714f8060487cae371cf86938be7e62/k8s/data-pipeline/mlab-oti.yml#L0)):*
Just to be sure, these empty yaml files are just place holders for the case that we want to define per-project variables? I notice the data-processing ones are empty too, but the prometheus-federation ones are not.

**Review by stephen-soltesz — COMMENTED** [review]
I've addressed your comments. Thank you for taking a look at the complex change!

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1002#-:-NchdR1IEkGBTEXQU5ym:b-is4of)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`config/federation/grafana/dashboards/Pipeline_AlternativeSLIs.json` line  at r1](https://reviewable.io/reviews/m-lab/prometheus-support/1002#-NchaLAN2gcllXleD8C0:-NchdT9F4Cfxp7S6dnYe:bhhwz7u) ([raw file](https://github.com/m-lab/prometheus-support/blob/3029460a46714f8060487cae371cf86938be7e62/config/federation/grafana/dashboards/Pipeline_AlternativeSLIs.json#L)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Just noting that it is a very mildly confusing that the file name of the dashboard is `Pipeline_AlternativeSLIs`, while the name of the dashboard in Grafana is `Pipeline SLIs` (minus "Alternative").
</blockquote></details>

I agree. Renamed.
___
*[`config/federation/grafana/dashboards/Stats_Pipeline_Monitoring.json` line 1652 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/1002#-NchcAJd-PWwJvTJnmo-:-NchdjwcERUxCActTpk7:b-5np55g) ([raw file](https://github.com/m-lab/prometheus-support/blob/3029460a46714f8060487cae371cf86938be7e62/config/federation/grafana/dashboards/Stats_Pipeline_Monitoring.json#L1652)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is `from`:`to` supposed to be set like this by default. When I load the dashboard it shows no data, and the date range is configured for a range from last year. I suspect this is unintentional.
</blockquote></details>

Fixed to last 24hr.
___
*[`config/federation/grafana/provisioning/datasources/data-pipeline_mlab-sandbox.yml.template` line 16 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/1002#-NchT_56-T8kRyNrPd9I:-NchdoKiEsyjr6YlzhY2:bwyr9ga) ([raw file](https://github.com/m-lab/prometheus-support/blob/3029460a46714f8060487cae371cf86938be7e62/config/federation/grafana/provisioning/datasources/data-pipeline_mlab-sandbox.yml.template#L16)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Just noting that I see this new domain in Cloud DNS in sandbox, but not in staging and mlab-oti. I imagine it will need to be manually created in staging and mlab-oti.
</blockquote></details>

Yes, using an IP allocated by deploying this change. So, deploy this change, lookup the IP, create the DNS entry.
___
*[`k8s/data-pipeline/mlab-oti.yml` line  at r1](https://reviewable.io/reviews/m-lab/prometheus-support/1002#-NchZBcw5d8dFBnn53fI:-Nche-Ku7u3MlT37aRzB:b8fgn2a) ([raw file](https://github.com/m-lab/prometheus-support/blob/3029460a46714f8060487cae371cf86938be7e62/k8s/data-pipeline/mlab-oti.yml#L)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Just to be sure, these empty yaml files are just place holders for the case that we want to define per-project variables? I notice the data-processing ones are empty too, but the prometheus-federation ones are not.
</blockquote></details>

That must be so. I don't know why these ended up in the PR. The empty files are already present in the "data-processing" directory https://github.com/m-lab/prometheus-support/tree/main/k8s/data-processing

Git may treat renames of empty files differently than files with content, so it looks like a new file even though it should only be a rename.

**Review by nkinkade — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/1002)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
