### PR TITLE
Implements end-to-end testing of wehe

### PR DESCRIPTION
**Pull request by nkinkade**
This PR introduces what I believe are the all the necessary pieces (for this repo, at least) to implement end-to-end testing of wehe via the new [wehe-cmdline client](https://github.com/dng24/wehe-cmdline). The changes presented here are dependent on these changes:

* https://github.com/m-lab/script-exporter-support/pull/33
* https://github.com/m-lab/locate/pull/51
* https://github.com/m-lab/access/pull/34

The script-exporter DaemonSet had a small bug in the form of the rollout strategy which previously defined a `maxUnavailable` of 25%, which is impossible to comply with in a 2 replicate deployment, causing stalled rollouts. This PR changes that to a static value of 1 instead of a percentage.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/805)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
One question to double check, but I'm imagining you've already verified this. So,

:lgtm: Great!

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/805#-:-MWeuRqq5DcZB-cv7eDy:b5blilf)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[config/federation/script-exporter/script_exporter.yml, line 13 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/805#-MWetu7k7YcFZDwKxNPh:-MWetu7l1tO51h9OMo0w:bspagy3) ([raw file](https://github.com/m-lab/prometheus-support/blob/a4ff7b69b2dafffbdd6ce0e2c8bdde406747e7e5/config/federation/script-exporter/script_exporter.yml#L13)):*
> ```YAML
>     script: EXPERIMENT=wehe cache_exit_code.sh 600
>       monitoring-token -machine=${TARGET} -service=wehe/replay --
>       java -jar wehe-cmdline/wehe-cmdline.jar -m ${MONITORING_URL} -n applemusic -t wehe-cmdline/res/ -c
> ```

Just double checking that this WAI? The `${MONITORING_URL}` gets evaluated at the right time? (it's hard to tell).

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/805)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/federation/script-exporter/script_exporter.yml, line 13 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/805#-MWetu7k7YcFZDwKxNPh:-MWexTRQ66uZeoyfF_QV:bi1eawc) ([raw file](https://github.com/m-lab/prometheus-support/blob/a4ff7b69b2dafffbdd6ce0e2c8bdde406747e7e5/config/federation/script-exporter/script_exporter.yml#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just double checking that this WAI? The `${MONITORING_URL}` gets evaluated at the right time? (it's hard to tell).
</blockquote></details>

Yeah, I checked and it seems to be WAI.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/805)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/federation/script-exporter/script_exporter.yml, line 13 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/805#-MWetu7k7YcFZDwKxNPh:-MWf2eEh4OtCCBCIeiPd:bbqw400) ([raw file](https://github.com/m-lab/prometheus-support/blob/fa2213a538c14d1b5bb04d089eb2ffe5f72b77b8/config/federation/script-exporter/script_exporter.yml#L13)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Yeah, I checked and it seems to be WAI.
</blockquote></details>

Hmmm. Looking at this again, I think I as wrong. My testing was done by logging into the container and emulating the script-exporter using shell scripting. But the only way I was able to get it to work was to put the java parts into a script file and then call the script from monitoring-token, else `${MONITORING_URL}` was evaluated by the shell at run time (and was empty).

My manual tests work, but `script_success` is failed for wehe in sandbox, with an exit code of 2, which means some bad flag. I gather what is happening here is that `${MONITORING_URL}` is being evaluated too early, which was your concern here.

I'll have to find a way to make this work.

**Review by stephen-soltesz — APPROVED** [review]
The change looks good. :lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/805#-:-MWfRPiJ96xpK0zvN86n:b-km1o9p)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
