### PR TITLE
Add TLS and basic auth to the sandbox cluster.

### PR DESCRIPTION
**Pull request by jheretic**
This pull request adds TLS endpoints via Letsencrypt certificates to Grafana, as well as basic authentication to Prometheus.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/203)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Thank you for the changes, Josh,

I've added a bunch of comments, but I don't think any are fundamental issues, just possible opportunities for simplification, or clarifying comments or questions for my understanding, or nit-picky formatting.

---

Review status: 0 of 20 files reviewed at latest revision, 20 unresolved discussions.

---

*[apply-global-prometheus.sh, line 27 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8Ixc1yZus86x74Lm6w:-L8Ixc1yZus86x74Lm6x:b-lh0ssx) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/apply-global-prometheus.sh#L27)):*
> ```Shell
> 
> export GRAFANA_DOMAIN=grafana.${PROJECT}.measurementlab.net
> export ALERTMANAGER_URL=https://alertmanager.${PROJECT}.measurementlab.net
> ```

To the degree possible, I would like URLs to work seamlessly -- In this case, I'm wondering if we can inline the basic auth user/password in the `ALERTMANAGER_URL` so that alerts sent to slack embed the correct credentials so we can just click on the links and they'll do the right thing, even if my browser hasn't cached the password already.

Would you be willing to add the inline user/passwd here?

---

*[apply-global-prometheus.sh, line 80 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8IvtyQENdj2WFSi9TE:-L8IvtyQENdj2WFSi9TF:b-aj8twp) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/apply-global-prometheus.sh#L80)):*
> ```Shell
> # TODO: kubectl v1.7  supports --from-env-file=
> kubectl create configmap grafana-env \
>     "--from-literal=domain=${GRAFANA_DOMAIN}" \
> ```

Does `root_url=` obviate the need for `domain=`?

http://docs.grafana.org/installation/configuration/#domain suggests `root_url` maybe the more important setting.

---

*[k8s/prometheus-federation/mlab-sandbox.yml, line 9 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8Iwe0b3Dmp6rXIiJh3:-L8Iwe0b3Dmp6rXIiJh4:bxwnj0j) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/mlab-sandbox.yml#L9)):*
> 35.226.80.19

Was allocating this IP a manual step taken before everything else?

---

*[k8s/prometheus-federation/mlab-staging.yml, line 8 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8IwpVH7q_rkMKNF8ko:-L8IwpVH7q_rkMKNF8kp:bvhie9l) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/mlab-staging.yml#L8)):*
> ```YAML
> PROMETHEUS_VOLUME_SIZE: 400Gi
> EXTERNAL_IP: 35.185.76.159
> TLS_EMAIL: support@measurementlab.net
> ```

Merges to `master` branch will auto-deploy to staging. Before we merge this change we will need to allocate a `TLS_IP` from staging using whatever the right steps are for that, and add it here.

---

*[k8s/prometheus-federation/deployments/grafana.yml, line 45 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8IxAeKbuM--de5sjvV:-L8IxAeKbuM--de5sjvW:b6iadju) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/grafana.yml#L45)):*
> ```YAML
>         - name: GF_SERVER_ROOT_URL
>           # The public facing domain name used to access grafana from a browser.
>           # The domain value is used in alert URLs generated by Grafana.
> ```

This comment looks copied from the one above. Is there a short summary of the significance of `root_url`?

---

*[k8s/prometheus-federation/deployments/grafana.yml, line 63 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8IxQAkTk7JGYoznODN:-L8IxQAkTk7JGYoznODO:bt0ck7v) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/grafana.yml#L63)):*
> ```YAML
>         ports:
>           - containerPort: 3000
>         readinessProbe:
> ```

What parts of the system depend on this readinessProbe? Please add a short comment with a hint.

---

*[k8s/prometheus-federation/deployments/kube-lego.yml, line 6 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8IyqtlCkDmyY37HSaF:-L8IyqtlCkDmyY37HSaG:b-krg7m5) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/kube-lego.yml#L6)):*
> ```YAML
>   namespace: kube-lego
> data:
>   # modify this to specify your address
> ```

Please update comment to something like the following (if it's true): "Let's Encrypt requires a valid contact email".

---

*[k8s/prometheus-federation/deployments/kube-lego.yml, line 8 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8IzceUC_EGS2JH-CBm:-L8IzceUC_EGS2JH-CBn:b-9h7jel) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/kube-lego.yml#L8)):*
> ```YAML
>   # modify this to specify your address
>   lego.email: "{{TLS_EMAIL}}"
>   # configure letsencrypt's production api
> ```

Please provide a hint to letsencrypt docs that describe the staging / prod APIs. Maybe this?
https://letsencrypt.org/docs/acme-protocol-updates/

---

*[k8s/prometheus-federation/deployments/kube-lego.yml, line 22 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8IztWvuqQqpN0nRYR6:-L8IztWvuqQqpN0nRYR7:b4np5dy) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/kube-lego.yml#L22)):*
> ```YAML
>     metadata:
>       labels:
>         # Required for the auto-create kube-lego-nginx service to work.
> ```

What does `kube-lego-nginx` refer to?

---

*[k8s/prometheus-federation/deployments/kube-lego.yml, line 37 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8J0iqvN64xbmqyMCyE:-L8J0iqvN64xbmqyMCyF:bvbzud1) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/kube-lego.yml#L37)):*
> ```YAML
>         - name: LEGO_EMAIL
>           valueFrom:
>             configMapKeyRef:
> ```

Since the lego email and url settings are static, can we inline those values here and eliminate the configmap definition above? This would simplify the config definition.

---

*[k8s/prometheus-federation/deployments/nginx-default.yml, line 1 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8J2duWspfdwWJgdxZf:-L8J2duWspfdwWJgdxZg:b-d5pggw) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/nginx-default.yml#L1)):*
> ```YAML
> apiVersion: extensions/v1beta1
> ```

What do you think of merging the files nginx-default.yml and nginx.yml? It looks like this one only exists b/c nginx.yml needs a default backend. So, we would never deploy this independently of nginx.yml.

---

*[k8s/prometheus-federation/deployments/nginx.yml, line 3 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8J3aXkCaSEPzDDVY2r:-L8J3aXkCaSEPzDDVY2s:b-uqnbf5) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/nginx.yml#L3)):*
> ```YAML
> apiVersion: v1
> data:
>   proxy-connect-timeout: "15"
> ```

Timeouts are seconds and sizes are bytes? If so, please add a short comment with that hint.

---

*[k8s/prometheus-federation/deployments/nginx.yml, line 29 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8JDoniqX-mQZBBZnm9:-L8JDoniqX-mQZBBZnmA:bc50a5m) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/nginx.yml#L29)):*
> ```YAML
>       containers:
>         - name: nginx
>           image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.12.0
> ```

Do you have a sense of how the internal plumbing works?

Does the nginx ingress work as an actual proxy (where all traffic passes through this container)? Or, does it just setup the plumbing between the LB and the backend services so that traffic passes through other parts of the system, bypassing the nginx ingress container entirely?

If it's the former, then I'm wondering if we should specify explicit cpu resources so that this is never the bottleneck on delivering data.

---

*[k8s/prometheus-federation/roles/rbac-kube-lego.yml, line 11 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8J4p1XOA6d-9Y8p6NM:-L8J4p1XOA6d-9Y8p6NN:b-4767j3) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/roles/rbac-kube-lego.yml#L11)):*
> ```YAML
>   name: kube-lego
> rules:
> - apiGroups:
> ```

Please add a short comment about what kube-lego does and why each resource is needed.

This is probably not accurate, but something like "kube-lego scans current pods and services to identify ingress definitions that need certificates loaded".

---

*[k8s/prometheus-federation/roles/rbac-kube-lego.yml, line 40 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8J4Zm7tqZaDtyeVk6H:-L8J4Zm7tqZaDtyeVk6I:bkh578b) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/roles/rbac-kube-lego.yml#L40)):*
> ```YAML
>   - delete
>   - watch
> - apiGroups:
> ```

This group appears to be a subset of the second group above. If both are necessary, please add a comment explaining why. If one can be eliminated, please do so.

---

*[k8s/prometheus-federation/roles/rbac-nginx.yml, line 17 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8J5UsDyfbxtdi6PlxD:-L8J5UsDyfbxtdi6PlxE:b-jubgjn) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/roles/rbac-nginx.yml#L17)):*
> ```YAML
>   name: nginx-ingress-clusterrole
> rules:
>   - apiGroups:
> ```

nit: indentation here looks inconsistent. Also, it is inconsistent with formatting in rbac-kube-lego.yml. Please use a consistent convention. I think rbac-kube-lego is preferable.

---

*[k8s/prometheus-federation/roles/rbac-nginx.yml, line 17 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8JA6JMzS7XJGDv1EHT:-L8JA6JMzS7XJGDv1EHU:bsrpwjv) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/roles/rbac-nginx.yml#L17)):*
> ```YAML
>   name: nginx-ingress-clusterrole
> rules:
>   - apiGroups:
> ```

Like above, please add a short comment about what nginx-ingress-controller does and why each resource is needed.

This is probably not accurate, but something like "nginx-ingress-controller scans service annotations for new paths and backends to forward".

---

*[k8s/prometheus-federation/services/alertmanager-tls-ingress.yml, line 1 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8J8heYDxQ9lSh2Y_tE:-L8J8heYDxQ9lSh2Y_tF:b-ullb7l) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/services/alertmanager-tls-ingress.yml#L1)):*
> ```YAML
> apiVersion: extensions/v1beta1
> ```

What do you think of combining the *-ingress and corresponding *-tls-service.yml files? Would we ever deploy one without the other?

---

*[k8s/prometheus-federation/services/alertmanager-tls-service.yml, line 19 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8J8B9O3E5KgyjJXutY:-L8J8B9O3E5KgyjJXutZ:b-u4xrpi) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/services/alertmanager-tls-service.yml#L19)):*
> ```YAML
>     run: alertmanager-server
>   sessionAffinity: None
>   type: NodePort
> ```

When we want to disable the legacy http public IPs, we simply delete the service alertmanager-public-service.yml from k8s and the file, and the new tls setup will keep working?

---

*[k8s/prometheus-federation/services/nginx.yml, line 1 at r1](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-L8J9Ou-efL9NNXZ4rsV:-L8J9Ou-efL9NNXZ4rsW:bi41odu) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/services/nginx.yml#L1)):*
> ```YAML
> apiVersion: v1
> ```

Can you help me understand the distinction between nginx-lb? and nginx.yml? I think I understand what nginx-lb is doing, since it specifies the TLS_IP. I'm less clear what this files is doing, since both files specify the same selector.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/prometheus-support/203#-:-L8JFB7gH2LbAtZBEs0s:bpkr4sr)*

**Comment by jheretic** [comment]
Review status: 0 of 20 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[apply-global-prometheus.sh, line 27 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8Ixc1yZus86x74Lm6w:-L8bxNia03AVwC1SJYXA:b-kk9myo) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/apply-global-prometheus.sh#L27)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

To the degree possible, I would like URLs to work seamlessly -- In this case, I'm wondering if we can inline the basic auth user/password in the `ALERTMANAGER_URL` so that alerts sent to slack embed the correct credentials so we can just click on the links and they'll do the right thing, even if my browser hasn't cached the password already.

Would you be willing to add the inline user/passwd here?
</blockquote></details>

I think this is doable. Currently the password is stored hashed as part of a username:password string in a Travis environment variable. The easiest thing would be to also store the plaintext password alongside in another Travis variable, but I don't like the idea of having two copies of the password that we have to keep in sync. My suggestion would be to store the username and password in plaintext in environment variables and add `apache2-utils` to the Travis environment so that the authentication string can be generated in the script. How does that sound?

---

*[apply-global-prometheus.sh, line 80 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8IvtyQENdj2WFSi9TE:-L8bzsqVECQaDTwuF-6g:brpradn) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/apply-global-prometheus.sh#L80)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does `root_url=` obviate the need for `domain=`?

http://docs.grafana.org/installation/configuration/#domain suggests `root_url` maybe the more important setting.
</blockquote></details>

I think you're correct that it can probably be removed.

---

*[k8s/prometheus-federation/mlab-sandbox.yml, line 9 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8Iwe0b3Dmp6rXIiJh3:-L8bvB8a53NfEEDcXxd9:b-y8bomv) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/mlab-sandbox.yml#L9)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

> 35.226.80.19

Was allocating this IP a manual step taken before everything else?
</blockquote></details>

Yes, I can add that to the README.

---

*[k8s/prometheus-federation/mlab-staging.yml, line 8 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8IwpVH7q_rkMKNF8ko:-L8c--Cs68b8HpQ82Gv-:brbwsbo) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/mlab-staging.yml#L8)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Merges to `master` branch will auto-deploy to staging. Before we merge this change we will need to allocate a `TLS_IP` from staging using whatever the right steps are for that, and add it here.
</blockquote></details>

Yes, that's true. I didn't have access to allocate that address for staging, but if you want to allocate an address I can add that to the configuration.

---

*[k8s/prometheus-federation/deployments/grafana.yml, line 45 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8IxAeKbuM--de5sjvV:-L8c-9Z33AdiIKzB72-4:blbrw8b) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/grafana.yml#L45)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This comment looks copied from the one above. Is there a short summary of the significance of `root_url`?
</blockquote></details>

I will add one. The root_url configuration was added hastily during deployment, as domain alone was insufficient for the oauth redirect.

---

*[k8s/prometheus-federation/deployments/kube-lego.yml, line 22 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8IztWvuqQqpN0nRYR6:-L8c8LVeAsbgdQLcUXSv:b-jib3dz) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/kube-lego.yml#L22)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What does `kube-lego-nginx` refer to?
</blockquote></details>

`kube-lego-nginx` is an automatically created service that actually handles the LetsEncrypt handshake (i.e., it's a service mapped to handle `.well-known` URLs). I can add a comment to that effect.

---

*[k8s/prometheus-federation/deployments/nginx.yml, line 29 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8JDoniqX-mQZBBZnm9:-L8c-ipk7go_ArXp5tk8:b-9hm28j) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/nginx.yml#L29)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do you have a sense of how the internal plumbing works?

Does the nginx ingress work as an actual proxy (where all traffic passes through this container)? Or, does it just setup the plumbing between the LB and the backend services so that traffic passes through other parts of the system, bypassing the nginx ingress container entirely?

If it's the former, then I'm wondering if we should specify explicit cpu resources so that this is never the bottleneck on delivering data.
</blockquote></details>

The nginx ingress does work as an actual proxy. What would you suggest as the resource allocations? You probably have a better idea of what kind of strain it's likely to be under.

---

*[k8s/prometheus-federation/deployments/nginx-default.yml, line 1 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8J2duWspfdwWJgdxZf:-L8c2zu925DQESu_xfll:b-a7ljwd) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/nginx-default.yml#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What do you think of merging the files nginx-default.yml and nginx.yml? It looks like this one only exists b/c nginx.yml needs a default backend. So, we would never deploy this independently of nginx.yml.
</blockquote></details>

Makes sense to me.

---

*[k8s/prometheus-federation/services/alertmanager-tls-ingress.yml, line 1 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8J8heYDxQ9lSh2Y_tE:-L8c8sSL5GCEWVD6mlcI:b-6bv50j) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/services/alertmanager-tls-ingress.yml#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What do you think of combining the *-ingress and corresponding *-tls-service.yml files? Would we ever deploy one without the other?
</blockquote></details>

Probably not. I can combine them.

---

*[k8s/prometheus-federation/services/alertmanager-tls-service.yml, line 19 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8J8B9O3E5KgyjJXutY:-L8c5VPqBoA8o8fQy7O3:bp8eu3) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/services/alertmanager-tls-service.yml#L19)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

When we want to disable the legacy http public IPs, we simply delete the service alertmanager-public-service.yml from k8s and the file, and the new tls setup will keep working?
</blockquote></details>

Yes, that's correct.

---

*[k8s/prometheus-federation/services/nginx.yml, line 1 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8J9Ou-efL9NNXZ4rsV:-L8c9AVHCZO5cZwfPiWU:bpy3h0d) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/services/nginx.yml#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can you help me understand the distinction between nginx-lb? and nginx.yml? I think I understand what nginx-lb is doing, since it specifies the TLS_IP. I'm less clear what this files is doing, since both files specify the same selector.
</blockquote></details>

Since I added the static IPs rather late in the process, it didn't occur to me that nginx.yml is now likely redundant. I'll resolve that.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203)*

**Comment by stephen-soltesz** [comment]
Thanks, Josh. I replied to a few comments -- looks like you're working on completing some changes. Let me know when you're ready for me to take another look.

---

Review status: 0 of 20 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[apply-global-prometheus.sh, line 27 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8Ixc1yZus86x74Lm6w:-L8clNTd6e0Cuizz-3QR:bxhnqn1) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/apply-global-prometheus.sh#L27)):*
<details><summary><i>Previously, jheretic (Josh King) wrote…</i></summary><blockquote>

I think this is doable. Currently the password is stored hashed as part of a username:password string in a Travis environment variable. The easiest thing would be to also store the plaintext password alongside in another Travis variable, but I don't like the idea of having two copies of the password that we have to keep in sync. My suggestion would be to store the username and password in plaintext in environment variables and add `apache2-utils` to the Travis environment so that the authentication string can be generated in the script. How does that sound?
</blockquote></details>

Ah, I didn't realize that the pre-digested password was the variable stored in travis. Yes, storing the plaintext password in travis and adding apache2-utils to the prep for the nginx proxy makes sense to me.

So that we can move forward with the staging deployment, let's do that in a subsequent PR.

---

*[apply-global-prometheus.sh, line 80 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8IvtyQENdj2WFSi9TE:-L8cliN32EYrLRRra34m:b2wiyc0) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/apply-global-prometheus.sh#L80)):*
<details><summary><i>Previously, jheretic (Josh King) wrote…</i></summary><blockquote>

I think you're correct that it can probably be removed.
</blockquote></details>

Okay, please do that or add a TODO so it can be done later.

---

*[k8s/prometheus-federation/mlab-sandbox.yml, line 9 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8Iwe0b3Dmp6rXIiJh3:-L8cltpnA6g_TpCXF_3m:btojbfq) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/mlab-sandbox.yml#L9)):*
<details><summary><i>Previously, jheretic (Josh King) wrote…</i></summary><blockquote>

Yes, I can add that to the README.
</blockquote></details>

Great.

---

*[k8s/prometheus-federation/mlab-staging.yml, line 8 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8IwpVH7q_rkMKNF8ko:-L8cmvA8DTY3DP9I9-qP:b-62s42s) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/mlab-staging.yml#L8)):*
<details><summary><i>Previously, jheretic (Josh King) wrote…</i></summary><blockquote>

Yes, that's true. I didn't have access to allocate that address for staging, but if you want to allocate an address I can add that to the configuration.
</blockquote></details>

How to do that? :)

---

*[k8s/prometheus-federation/deployments/nginx.yml, line 29 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8JDoniqX-mQZBBZnm9:-L8cmLRZD5cTwHPMEkma:bac6kgc) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/deployments/nginx.yml#L29)):*
<details><summary><i>Previously, jheretic (Josh King) wrote…</i></summary><blockquote>

The nginx ingress does work as an actual proxy. What would you suggest as the resource allocations? You probably have a better idea of what kind of strain it's likely to be under.
</blockquote></details>

Let's start with 1 CPU.

The memory is probably proportionate to the number of connections... let's leave the default for now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-:-L8cmzT7C7dswsK4vWTZ:bclvmfm)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 20 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[k8s/prometheus-federation/mlab-staging.yml, line 8 at r1](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8IwpVH7q_rkMKNF8ko:-L8cp_lDAlhKtCgOM9l6:bg86tf8) ([raw file](https://github.com/m-lab/prometheus-support/blob/e00972920d9a172bc792772bd3c345f9219b34d0/k8s/prometheus-federation/mlab-staging.yml#L8)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

How to do that? :)
</blockquote></details>

Please use: 35.196.34.1

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203)*

**Comment by stephen-soltesz** [comment]
With the final changes, this :lgtm:

---

Reviewed 2 of 20 files at r1, 3 of 10 files at r2, 6 of 13 files at r3.
Review status: 11 of 15 files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 57 at r3](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8dBcZi5a1JfdP_-zYA:-L8dBcZi5a1JfdP_-zYB:byn8ki5) ([raw file](https://github.com/m-lab/prometheus-support/blob/9fa7a79bb835b31cadda72ced95ea53c2c20a9e8/README.md#L57)):*
> ```Markdown
> are associated with a single zone. It is necessary to configure a static IP 
> by going to:
>     
> ```

nit: please remove trailing whitespace.

---

*[k8s/prometheus-federation/mlab-oti.yml, line 8 at r3](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8dFGxoCDYj8K0-X77m:-L8dFGxoCDYj8K0-X77n:b-2uw8z8) ([raw file](https://github.com/m-lab/prometheus-support/blob/9fa7a79bb835b31cadda72ced95ea53c2c20a9e8/k8s/prometheus-federation/mlab-oti.yml#L8)):*
> ```YAML
> PROMETHEUS_VOLUME_SIZE: 400Gi
> EXTERNAL_IP: 35.184.81.106
> TLS_EMAIL: support@measurementlab.net
> ```

While we're here, please also add `TLS_IP: 35.194.63.109` for mlab-oti.

---

*[k8s/prometheus-federation/deployments/grafana.yml, line 57 at r3](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-L8dDE8BE-U3QyGkJqTG:-L8dDE8BE-U3QyGkJqTH:bb43rl1) ([raw file](https://github.com/m-lab/prometheus-support/blob/9fa7a79bb835b31cadda72ced95ea53c2c20a9e8/k8s/prometheus-federation/deployments/grafana.yml#L57)):*
> ```YAML
>         ports:
>           - containerPort: 3000
>         # Many ingresses expect an HTTP code 200 on port 80 at path '/', for 
> ```

nit: looks like there is trailing whitespace all over.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/prometheus-support/203#-:-L8dFTNfBjiNsPBB3yrV:b9bxkrp)*

**Pull request merged**
