### PR TITLE
Add oauth2-proxy in front of Prometheus/Grafana

### PR DESCRIPTION
**Pull request by robertodauria**
This PR deploys oauth2-proxy and configures the Grafana and Prometheus ingresses to authenticate via OAuth. The old HTTP basic authentication for Prometheus is retained at prometheus.$PROJECT.measurementlab.net to still allow automation to easily access to it.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/780)

### CODE REVIEW

**Review by nkinkade — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/780)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[k8s/prometheus-federation/deployments/oauth2-proxy.yml, line 29 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSijonqDBJyWpIl6-0y:-MSijonqDBJyWpIl6-0z:b-epqcdm) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/deployments/oauth2-proxy.yml#L29)):*
> ```YAML
>         - --email-domain=measurementlab.net
>         - --email-domain={{GCLOUD_PROJECT}}.iam.gserviceaccount.com
>         - --email-domain=northeastern.edu
> ```

I think we can remove "northeastern.edu", as we have already verified that it doesn't work.
___
*[k8s/prometheus-federation/deployments/oauth2-proxy.yml, line 30 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSijv8aEE0ejqMIzcxt:-MSijv8aEE0ejqMIzcxu:btpv3dg) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/deployments/oauth2-proxy.yml#L30)):*
> ```YAML
>         - --email-domain={{GCLOUD_PROJECT}}.iam.gserviceaccount.com
>         - --email-domain=northeastern.edu
>         - --email-domain=husky.neu.edu
> ```

Do you know if it's possible to use only "neu.edu" here and not worry about subdomains, which could possibly change?
___
*[k8s/prometheus-federation/services/grafana-tls-oauth.yml, line 2 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSikVD0-k8vJsGjEL6K:-MSikVD0-k8vJsGjEL6L:bstdrva) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/services/grafana-tls-oauth.yml#L2)):*
> ```YAML
> # This Ingress makes sure oauth2-proxy intercepts requests going to the /oauth2
> # path. This path *must not* be secured, to prevent a redirection loop.
> ```

Could you detail what you mean by "path" and "secured" here? I notice that this ingress has "tls" in the name, a "tls" config section" and an annotation for "tls-acme", all of which speak to me of securing this resource. Maybe just elaborate what you mean in the comment.
___
*[k8s/prometheus-federation/services/oauth2-proxy.yml, line 15 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSimGqq7Ryv52cC-ErN:-MSimGqr5GMbqhEVG6LF:bubpjqv) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/services/oauth2-proxy.yml#L15)):*
> ```YAML
>   selector:
>     run: oauth2-proxy
>   type: NodePort
> ```

Is this really supposed to of type `NodePort`?
___
*[k8s/prometheus-federation/services/prometheus-tls-basic.yml, line 4 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSimPf4DPFCI_vY7oUW:-MSimPf4DPFCI_vY7oUX:bdr47jg) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/services/prometheus-tls-basic.yml#L4)):*
> ```YAML
> # for easier machine access to Prometheus.
> apiVersion: extensions/v1beta1
> kind: Ingress
> ```

We've now got numerous `Ingress` resources, all of which are currently in the `services/` subdirectory. Is it time to create a new `ingresses/` subdirectory for these?
___
*[k8s/prometheus-federation/services/prometheus-tls-oauth.yml, line 23 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSimpN_1FK60YZX-Z1X:-MSimpN_1FK60YZX-Z1Y:b-4qi8sl) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/services/prometheus-tls-oauth.yml#L23)):*
> ```YAML
>           serviceName: oauth2-proxy
>           servicePort: 4180
>         path: /oauth2
> ```

Does this mean that interactive users will need to access Prometheus at URLs that end in `/oauth2`, or is this just something specific to the oauth2-proxy? Same for the Grafana oauth Ingress.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/780)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @robertodauria)

___
*[k8s/prometheus-federation/deployments/oauth2-proxy.yml, line 29 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSijonqDBJyWpIl6-0y:-MSis_QV9RWDx6bJMfEm:b-896fix) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/deployments/oauth2-proxy.yml#L29)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I think we can remove "northeastern.edu", as we have already verified that it doesn't work.
</blockquote></details>

Done.
___
*[k8s/prometheus-federation/deployments/oauth2-proxy.yml, line 30 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSijv8aEE0ejqMIzcxt:-MSirBby4IMWLH0Ax7L0:bmjsnfg) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/deployments/oauth2-proxy.yml#L30)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Do you know if it's possible to use only "neu.edu" here and not worry about subdomains, which could possibly change?
</blockquote></details>

AFAIK it should be possible. I changed it to neu.edu.
___
*[k8s/prometheus-federation/services/grafana-tls-oauth.yml, line 2 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSikVD0-k8vJsGjEL6K:-MSisizj7YhDnENEMUeF:b8b7jol) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/services/grafana-tls-oauth.yml#L2)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Could you detail what you mean by "path" and "secured" here? I notice that this ingress has "tls" in the name, a "tls" config section" and an annotation for "tls-acme", all of which speak to me of securing this resource. Maybe just elaborate what you mean in the comment.
</blockquote></details>

I changed the comment a bit. 

Basically it works like this: the user accesses `/` as usual, nginx detects there is no session cookie (or it expired) and redirects the user to `/oauth2/start?...` which is the OAuth authentication flow. `/oauth2` is handled by oauth2-proxy, and it must be not protected or it wouldn't be accessible by users before they have a session cookie, generating a redirection loop. It also needs to be handled by any oauth-protected hostname, which is why there is one Ingress for prometheus and one for grafana. Both point to the same oauth2-proxy deployment when the user requests `/oauth2`.
___
*[k8s/prometheus-federation/services/oauth2-proxy.yml, line 15 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSimGqq7Ryv52cC-ErN:-MSiuiG96nmsjrHxWxv3:b-ir1ujq) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/services/oauth2-proxy.yml#L15)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is this really supposed to of type `NodePort`?
</blockquote></details>

I think `NodePort` is referring to the internal IP of the GKE node (this is different on platform cluster, where `NodePort` actually exposes a pod to the world). I basically took it from Grafana, which has `NodePort` and is only exposed via an Ingress -- no way to directly access the node other than going through that ingress, AFAIK. I may be wrong, though. Does it correspond to your knowledge of `NodePort` in the context of GKE?
___
*[k8s/prometheus-federation/services/prometheus-tls-basic.yml, line 4 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSimPf4DPFCI_vY7oUW:-MSivbAk2_-4a8p8t5-4:bwa2a9x) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/services/prometheus-tls-basic.yml#L4)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

We've now got numerous `Ingress` resources, all of which are currently in the `services/` subdirectory. Is it time to create a new `ingresses/` subdirectory for these?
</blockquote></details>

Good idea -- WIP.
___
*[k8s/prometheus-federation/services/prometheus-tls-oauth.yml, line 23 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSimpN_1FK60YZX-Z1X:-MSivUan-Zv6qZv62w8m:br8g9lf) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/services/prometheus-tls-oauth.yml#L23)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Does this mean that interactive users will need to access Prometheus at URLs that end in `/oauth2`, or is this just something specific to the oauth2-proxy? Same for the Grafana oauth Ingress.
</blockquote></details>

Explained in the comment above, users will keep using `/`.

**Review by nkinkade — APPROVED** [review]
> Reviewed 6 of 9 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/780)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @robertodauria)

___
*[apply-global-prometheus.sh, line 50 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSj2QwX-xl3n0sRg3dm:-MSj2QwX-xl3n0sRg3dn:bdskase) ([raw file](https://github.com/m-lab/prometheus-support/blob/beee35494ec50a0ebf11177575b10ed7ca4208de/apply-global-prometheus.sh#L50)):*
> ```Shell
> export OAUTH_PROXY_CLIENT_ID=OAUTH_PROXY_CLIENT_ID_${PROJECT/-/_}
> export OAUTH_PROXY_CLIENT_SECRET=OAUTH_PROXY_CLIENT_SECRET_${PROJECT/-/_}
> export OAUTH_PROXY_COOKIE_SECRET=OAUTH_PROXY_COOKIE_SECRET_${PROJECT/-/_}
> ```

I assume all of the above have been created manually as Travis-CI env variables?
___
*[k8s/prometheus-federation/services/oauth2-proxy.yml, line 15 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSimGqq7Ryv52cC-ErN:-MSj0Lw2A097tsTO7Udf:bliypov) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/services/oauth2-proxy.yml#L15)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I think `NodePort` is referring to the internal IP of the GKE node (this is different on platform cluster, where `NodePort` actually exposes a pod to the world). I basically took it from Grafana, which has `NodePort` and is only exposed via an Ingress -- no way to directly access the node other than going through that ingress, AFAIK. I may be wrong, though. Does it correspond to your knowledge of `NodePort` in the context of GKE?
</blockquote></details>

As far as I understand, [NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport) is a type of Service which causes kube-proxy to expose a random port on _every single node_ in the cluster which redirects into the Service. It is a way to possibly expose a Service externally without using a loadbalancer, assuming that port on nodes isn't firewalled (which it likely is in our case). I would have more expected a `ClusterIP` type here. This probably doesn't make a practical difference for us, but it might be worth experiment removing the `type` or explicitly defining it as a `ClusterIP` type, assuming things aren't actually using the "NodePort" functionality.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/780)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[apply-global-prometheus.sh, line 50 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSj2QwX-xl3n0sRg3dm:-MSjEP2E3jVf2r00dCG7:bb77ufg) ([raw file](https://github.com/m-lab/prometheus-support/blob/beee35494ec50a0ebf11177575b10ed7ca4208de/apply-global-prometheus.sh#L50)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I assume all of the above have been created manually as Travis-CI env variables?
</blockquote></details>

Yes.
___
*[k8s/prometheus-federation/services/oauth2-proxy.yml, line 15 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSimGqq7Ryv52cC-ErN:-MSjH-N34e7LDRWGs3Zp:b-tlbl6u) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/services/oauth2-proxy.yml#L15)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

As far as I understand, [NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport) is a type of Service which causes kube-proxy to expose a random port on _every single node_ in the cluster which redirects into the Service. It is a way to possibly expose a Service externally without using a loadbalancer, assuming that port on nodes isn't firewalled (which it likely is in our case). I would have more expected a `ClusterIP` type here. This probably doesn't make a practical difference for us, but it might be worth experiment removing the `type` or explicitly defining it as a `ClusterIP` type, assuming things aren't actually using the "NodePort" functionality.
</blockquote></details>

I've changed it to ClusterIP. As discussed on Slack, I would also move Grafana/Prometheus from NodePort + ClusterIP to ClusterIP only on a separate PR.
___
*[k8s/prometheus-federation/services/prometheus-tls-basic.yml, line 4 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/780#-MSimPf4DPFCI_vY7oUW:-MSjDzW82re8kT2GCDQ6:bje6ccz) ([raw file](https://github.com/m-lab/prometheus-support/blob/71850608564e4bc0d5f8ade9f31e9a9531ec5128/k8s/prometheus-federation/services/prometheus-tls-basic.yml#L4)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Good idea -- WIP.
</blockquote></details>

Actually, I would do this on a separate PR. There is quite a bit of stuff to move and I want to make sure everything works afterwards.

**Review by nkinkade — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/780)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
